// Auto-generated by scripts/gen_parity_tests.py from docs/runtime-parity.md.
// Module: node:events
// This file is a byte-for-byte parity test against `node --experimental-strip-types`.
// Edit the TODO lines below to exercise each API; rerun
// `./run_parity_tests.sh --filter test_parity_events` to verify.

import * as events from "node:events";
import { EventEmitter } from "node:events";


// ── Classes ──
// class EventEmitter — instance methods
try {
  const em = new EventEmitter();
  let total = 0;
  em.on("inc", (n: number) => { total += n; });
  em.on("inc", (n: number) => { total += n * 10; });
  em.emit("inc", 1);
  em.emit("inc", 2);
  console.log("EventEmitter.on/emit total:", total);

  console.log("EventEmitter.listenerCount('inc'):", em.listenerCount("inc"));
  console.log("EventEmitter.listenerCount('nope'):", em.listenerCount("nope"));
  console.log("EventEmitter.eventNames():", em.eventNames());

  const onceVals: number[] = [];
  em.once("solo", (n: number) => { onceVals.push(n); });
  em.emit("solo", 7);
  em.emit("solo", 8);
  console.log("EventEmitter.once values:", onceVals);

  const addListenerSeen: number[] = [];
  const handler = (n: number) => { addListenerSeen.push(n); };
  em.addListener("alias", handler);
  em.emit("alias", 1);
  em.removeListener("alias", handler);
  em.emit("alias", 2);
  console.log("EventEmitter.addListener/removeListener:", addListenerSeen);

  const order: string[] = [];
  em.on("ord", () => { order.push("b"); });
  em.prependListener("ord", () => { order.push("a"); });
  em.emit("ord");
  console.log("EventEmitter.prependListener order:", order);

  const onceOrder: string[] = [];
  em.on("ord2", () => { onceOrder.push("b"); });
  em.prependOnceListener("ord2", () => { onceOrder.push("a"); });
  em.emit("ord2");
  em.emit("ord2");
  console.log("EventEmitter.prependOnceListener order:", onceOrder);

  const listed = em.listeners("inc");
  console.log("EventEmitter.listeners('inc') count:", listed.length);
  const raw = em.rawListeners("inc");
  console.log("EventEmitter.rawListeners('inc') count:", raw.length);

  em.setMaxListeners(42);
  console.log("EventEmitter.getMaxListeners():", em.getMaxListeners());

  em.removeAllListeners("inc");
  console.log("EventEmitter after removeAllListeners('inc') count:", em.listenerCount("inc"));
  em.removeAllListeners();
  console.log("EventEmitter after removeAllListeners() names:", em.eventNames());
} catch (e: any) { console.log("EventEmitter ERR:", e && e.message); }

// ── Functions ──
// events.once(emitter, name) — Promise
try {
  const em = new EventEmitter();
  const p = events.once(em, "ready");
  em.emit("ready", "value-1", "value-2");
  const result = await p;
  console.log("events.once resolved length:", (result as any[]).length, "first:", (result as any[])[0]);
} catch (e: any) { console.log("events.once ERR:", e && e.message); }

// events.on(emitter, eventName) — async iterator
try {
  const em = new EventEmitter();
  const iter = events.on(em, "data");
  em.emit("data", 1);
  em.emit("data", 2);
  em.emit("data", 3);
  // Schedule close so the iterator terminates after we consume 3.
  Promise.resolve().then(() => {
    // Closes the async iterator without throwing.
    em.emit("close");
  });
  const collected: number[] = [];
  let consumed = 0;
  for await (const ev of iter) {
    collected.push((ev as any[])[0]);
    consumed++;
    if (consumed >= 3) break;
  }
  console.log("events.on collected:", collected);
} catch (e: any) { console.log("events.on ERR:", e && e.message); }

// events.getEventListeners(emitter, eventName)
try {
  const em = new EventEmitter();
  em.on("x", () => {});
  em.on("x", () => {});
  const ls = events.getEventListeners(em, "x");
  console.log("events.getEventListeners count:", ls.length);
} catch (e: any) { console.log("events.getEventListeners ERR:", e && e.message); }

// events.getMaxListeners(emitter)
try {
  const em = new EventEmitter();
  em.setMaxListeners(15);
  console.log("events.getMaxListeners:", events.getMaxListeners(em));
} catch (e: any) { console.log("events.getMaxListeners ERR:", e && e.message); }

// events.setMaxListeners(n, ...targets)
try {
  const em = new EventEmitter();
  events.setMaxListeners(20, em);
  console.log("events.setMaxListeners then get:", em.getMaxListeners());
} catch (e: any) { console.log("events.setMaxListeners ERR:", e && e.message); }

// events.listenerCount(emitter, eventName) — static (deterministic)
try {
  const em = new EventEmitter();
  em.on("evt", () => {});
  em.on("evt", () => {});
  em.on("evt", () => {});
  console.log("events.listenerCount(em,'evt'):", events.listenerCount(em, "evt"));
  console.log("events.listenerCount(em,'none'):", events.listenerCount(em, "none"));
  // Also exercise the static EventEmitter.listenerCount form.
  console.log("EventEmitter.listenerCount(em,'evt'):", EventEmitter.listenerCount(em, "evt"));
} catch (e: any) { console.log("events.listenerCount ERR:", e && e.message); }

// events.addAbortListener(signal, listener)
try {
  const ctrl = new AbortController();
  let fired = 0;
  const disposable = events.addAbortListener(ctrl.signal, () => { fired++; });
  ctrl.abort();
  console.log("events.addAbortListener fired:", fired);
  console.log("events.addAbortListener returned Disposable:", typeof (disposable as any)[Symbol.dispose] === "function");
} catch (e: any) { console.log("events.addAbortListener ERR:", e && e.message); }

// ── Constants / Properties ──
console.log("events.defaultMaxListeners:", events.defaultMaxListeners);
console.log("events.errorMonitor:", events.errorMonitor);
console.log("events.captureRejections:", events.captureRejections);
console.log("events.captureRejectionSymbol:", events.captureRejectionSymbol);

// ── Events emitted by EventEmitter ──
// 'newListener' — fires before a listener is added.
try {
  const em = new EventEmitter();
  const seen: string[] = [];
  em.on("newListener", (event: string) => { seen.push(event); });
  em.on("hello", () => {});
  em.on("world", () => {});
  console.log("'newListener' seen:", seen);
} catch (e: any) { console.log("'newListener' ERR:", e && e.message); }

// 'removeListener' — fires after a listener is removed.
try {
  const em = new EventEmitter();
  const seen: string[] = [];
  em.on("removeListener", (event: string) => { seen.push(event); });
  const h = () => {};
  em.on("greet", h);
  em.removeListener("greet", h);
  console.log("'removeListener' seen:", seen);
} catch (e: any) { console.log("'removeListener' ERR:", e && e.message); }

// PERRY-SKIP: captureRejections async-rejection routing — relies on Symbol.for('nodejs.rejection') method dispatch which is unstable in Perry today.
// PERRY-SKIP: EventEmitterAsyncResource — async_hooks integration, output is non-deterministic (asyncId varies).

// Coverage: 4 auto-emitted, 10 TODO, 0 skip-listed.

/*
@covers
crates/perry-stdlib/src/events.rs:
  - js_event_emitter_emit
  - js_event_emitter_emit0
  - js_event_emitter_listener_count
  - js_event_emitter_new
  - js_event_emitter_on
  - js_event_emitter_remove_all_listeners
  - js_event_emitter_remove_listener
*/
