// Auto-generated by scripts/gen_parity_tests.py from docs/runtime-parity.md.
// Module: node:tls
// This file is a byte-for-byte parity test against `node --experimental-strip-types`.
// Edit the TODO lines below to exercise each API; rerun
// `./run_parity_tests.sh --filter test_parity_tls` to verify.

import * as tls from "node:tls";


// ── Functions ──
// Type-probes only for surfaces that would dial out or need key/cert material.
console.log("tls.checkServerIdentity typeof:", typeof tls.checkServerIdentity);
console.log("tls.connect typeof:", typeof tls.connect);
// PERRY-SKIP: tls.connect(port,host) requires live TLS endpoint (non-deterministic).
// PERRY-SKIP: tls.connect(path) requires live TLS IPC endpoint.
try {
  const ctx = tls.createSecureContext({});
  console.log("tls.createSecureContext typeof:", typeof ctx);
} catch (e) {
  console.log("tls.createSecureContext error:", (e as Error).message);
}
console.log("tls.createSecurePair typeof:", typeof tls.createSecurePair);
try {
  const srv = tls.createServer({});
  console.log("tls.createServer typeof:", typeof srv);
  srv.close();
  console.log("tls.createServer close: ok");
} catch (e) {
  console.log("tls.createServer error:", (e as Error).message);
}
console.log("tls.setDefaultCACertificates typeof:", typeof tls.setDefaultCACertificates);
console.log("tls.getCACertificates typeof:", typeof tls.getCACertificates);
try {
  const ciphers = tls.getCiphers();
  console.log("tls.getCiphers length:", ciphers.length);
  console.log("tls.getCiphers first3:", ciphers.slice(0, 3));
} catch (e) {
  console.log("tls.getCiphers error:", (e as Error).message);
}

// ── Module Properties / Constants ──
console.log("tls.DEFAULT_ECDH_CURVE:", tls.DEFAULT_ECDH_CURVE);
console.log("tls.DEFAULT_MAX_VERSION:", tls.DEFAULT_MAX_VERSION);
console.log("tls.DEFAULT_MIN_VERSION:", tls.DEFAULT_MIN_VERSION);
console.log("tls.DEFAULT_CIPHERS typeof:", typeof tls.DEFAULT_CIPHERS);
try {
  const roots = tls.rootCertificates;
  console.log("tls.rootCertificates shape:",
    Array.isArray(roots),
    Object.isFrozen(roots),
    roots.length > 1,
    typeof roots[0],
    roots[0]?.startsWith("-----BEGIN CERTIFICATE-----"),
  );
} catch (e) {
  console.log("tls.rootCertificates error:", (e as Error).message);
}
console.log("tls.CLIENT_RENEG_LIMIT:", tls.CLIENT_RENEG_LIMIT);
console.log("tls.CLIENT_RENEG_WINDOW:", tls.CLIENT_RENEG_WINDOW);

// Coverage: 7 auto-emitted, 9 filled, 2 skip-listed.
