// Auto-generated by generate.py — do not hand-edit; rerun the generator.
// Module #000 in the #808 init-scale chain. Each module imports its
// predecessor so Perry's module init order has to walk the chain end
// to end (#684 conditions). The class+const pair gives the harness two
// independent state-isolation probes.
// (m000 has no predecessor — the chain starts here.)
export const VAL_000: number = 1000;

export class Cls_000 {
  // `tag()` returns a string baked from the module index. After 300+
  // inits, Perry must still dispatch this method on a `Cls_000`
  // instance (not Cls_0 / Cls_299 / a phantom shape) and the return
  // must be a string (not 0, undefined, or a NaN-box leak).
  tag(): string {
    return "Cls_000";
  }
}
