// Auto-generated by generate.py — do not hand-edit; rerun the generator.
// Module #007 in the #808 init-scale chain. Each module imports its
// predecessor so Perry's module init order has to walk the chain end
// to end (#684 conditions). The class+const pair gives the harness two
// independent state-isolation probes.
import { VAL_006 } from "./m006";
// Reference the predecessor in a top-level expression to
// guarantee the import survives DCE and the predecessor
// init runs before ours.
const _chain_007: number = VAL_006 + 1;
if (_chain_007 < 0) throw new Error("chain check");
export const VAL_007: number = 1007;

export class Cls_007 {
  // `tag()` returns a string baked from the module index. After 300+
  // inits, Perry must still dispatch this method on a `Cls_007`
  // instance (not Cls_0 / Cls_299 / a phantom shape) and the return
  // must be a string (not 0, undefined, or a NaN-box leak).
  tag(): string {
    return "Cls_007";
  }
}
