// Auto-generated by generate.py — do not hand-edit; rerun the generator.
// Module #063 in the #808 init-scale chain. Each module imports its
// predecessor so Perry's module init order has to walk the chain end
// to end (#684 conditions). The class+const pair gives the harness two
// independent state-isolation probes.
import { VAL_062 } from "./m062";
// Reference the predecessor in a top-level expression to
// guarantee the import survives DCE and the predecessor
// init runs before ours.
const _chain_063: number = VAL_062 + 1;
if (_chain_063 < 0) throw new Error("chain check");
export const VAL_063: number = 1063;

export class Cls_063 {
  // `tag()` returns a string baked from the module index. After 300+
  // inits, Perry must still dispatch this method on a `Cls_063`
  // instance (not Cls_0 / Cls_299 / a phantom shape) and the return
  // must be a string (not 0, undefined, or a NaN-box leak).
  tag(): string {
    return "Cls_063";
  }
}
