// Auto-generated by generate.py — do not hand-edit; rerun the generator.
// Module #165 in the #808 init-scale chain. Each module imports its
// predecessor so Perry's module init order has to walk the chain end
// to end (#684 conditions). The class+const pair gives the harness two
// independent state-isolation probes.
import { VAL_164 } from "./m164";
// Reference the predecessor in a top-level expression to
// guarantee the import survives DCE and the predecessor
// init runs before ours.
const _chain_165: number = VAL_164 + 1;
if (_chain_165 < 0) throw new Error("chain check");
export const VAL_165: number = 1165;

export class Cls_165 {
  // `tag()` returns a string baked from the module index. After 300+
  // inits, Perry must still dispatch this method on a `Cls_165`
  // instance (not Cls_0 / Cls_299 / a phantom shape) and the return
  // must be a string (not 0, undefined, or a NaN-box leak).
  tag(): string {
    return "Cls_165";
  }
}
