// Auto-generated by generate.py — do not hand-edit; rerun the generator.
// Module #174 in the #808 init-scale chain. Each module imports its
// predecessor so Perry's module init order has to walk the chain end
// to end (#684 conditions). The class+const pair gives the harness two
// independent state-isolation probes.
import { VAL_173 } from "./m173";
// Reference the predecessor in a top-level expression to
// guarantee the import survives DCE and the predecessor
// init runs before ours.
const _chain_174: number = VAL_173 + 1;
if (_chain_174 < 0) throw new Error("chain check");
export const VAL_174: number = 1174;

export class Cls_174 {
  // `tag()` returns a string baked from the module index. After 300+
  // inits, Perry must still dispatch this method on a `Cls_174`
  // instance (not Cls_0 / Cls_299 / a phantom shape) and the return
  // must be a string (not 0, undefined, or a NaN-box leak).
  tag(): string {
    return "Cls_174";
  }
}
