// Auto-generated by generate.py — do not hand-edit; rerun the generator.
// Module #195 in the #808 init-scale chain. Each module imports its
// predecessor so Perry's module init order has to walk the chain end
// to end (#684 conditions). The class+const pair gives the harness two
// independent state-isolation probes.
import { VAL_194 } from "./m194";
// Reference the predecessor in a top-level expression to
// guarantee the import survives DCE and the predecessor
// init runs before ours.
const _chain_195: number = VAL_194 + 1;
if (_chain_195 < 0) throw new Error("chain check");
export const VAL_195: number = 1195;

export class Cls_195 {
  // `tag()` returns a string baked from the module index. After 300+
  // inits, Perry must still dispatch this method on a `Cls_195`
  // instance (not Cls_0 / Cls_299 / a phantom shape) and the return
  // must be a string (not 0, undefined, or a NaN-box leak).
  tag(): string {
    return "Cls_195";
  }
}
