// Auto-generated by generate.py — do not hand-edit; rerun the generator.
// Module #265 in the #808 init-scale chain. Each module imports its
// predecessor so Perry's module init order has to walk the chain end
// to end (#684 conditions). The class+const pair gives the harness two
// independent state-isolation probes.
import { VAL_264 } from "./m264";
// Reference the predecessor in a top-level expression to
// guarantee the import survives DCE and the predecessor
// init runs before ours.
const _chain_265: number = VAL_264 + 1;
if (_chain_265 < 0) throw new Error("chain check");
export const VAL_265: number = 1265;

export class Cls_265 {
  // `tag()` returns a string baked from the module index. After 300+
  // inits, Perry must still dispatch this method on a `Cls_265`
  // instance (not Cls_0 / Cls_299 / a phantom shape) and the return
  // must be a string (not 0, undefined, or a NaN-box leak).
  tag(): string {
    return "Cls_265";
  }
}
