// Auto-generated by generate.py — do not hand-edit; rerun the generator.
// Module #289 in the #808 init-scale chain. Each module imports its
// predecessor so Perry's module init order has to walk the chain end
// to end (#684 conditions). The class+const pair gives the harness two
// independent state-isolation probes.
import { VAL_288 } from "./m288";
// Reference the predecessor in a top-level expression to
// guarantee the import survives DCE and the predecessor
// init runs before ours.
const _chain_289: number = VAL_288 + 1;
if (_chain_289 < 0) throw new Error("chain check");
export const VAL_289: number = 1289;

export class Cls_289 {
  // `tag()` returns a string baked from the module index. After 300+
  // inits, Perry must still dispatch this method on a `Cls_289`
  // instance (not Cls_0 / Cls_299 / a phantom shape) and the return
  // must be a string (not 0, undefined, or a NaN-box leak).
  tag(): string {
    return "Cls_289";
  }
}
