//! Feature parity rows for advanced widgets (Sheet/Toolbar),
//! `perry_system_*` APIs, and web-only FFI surfaces.

use crate::{Category::*, Feature, S, U};

pub(crate) const ROWS: &[Feature] = &[
    // ── Advanced (Sheet, Toolbar) ────────────────────────────────────────
    Feature {
        name: "perry_ui_sheet_create",
        category: Advanced,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_sheet_present",
        category: Advanced,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_sheet_dismiss",
        category: Advanced,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_toolbar_create",
        category: Advanced,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_toolbar_add_item",
        category: Advanced,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_toolbar_attach",
        category: Advanced,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── System API ───────────────────────────────────────────────────────
    Feature {
        name: "perry_system_open_url",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // #917: system share sheet. macOS has the real NSSharingServicePicker
    // implementation; every other platform is a no-op stub today
    // (per-platform native impls land as #917 follow-ups).
    Feature {
        name: "perry_system_share_text",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_system_share_url",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // #675: App Group / cross-process shared storage. macOS has the
    // real NSUserDefaults(suiteName:) impl; iOS has the in-process
    // HashMap MVP; every other platform is a first-call-warning stub.
    Feature {
        name: "perry_system_app_group_set",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_system_app_group_get",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_system_app_group_delete",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_system_is_dark_mode",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // Bug-report-flow utility: stable OS-version string. macOS has
    // the real impl via NSProcessInfo; every other platform is a
    // first-call-warning stub awaiting its native implementation.
    Feature {
        name: "perry_system_get_os_version",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_system_preferences_set",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_system_preferences_get",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_system_keychain_save",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_system_keychain_get",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_system_keychain_delete",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_system_notification_send",
        category: SystemApi,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_system_notification_register_remote",
        category: SystemApi,
        macos: S,
        ios: S,
        android: U,
        gtk4: U,
        windows: U,
        web: U,
        web_name: None,
    },
    Feature {
        name: "perry_system_notification_on_receive",
        category: SystemApi,
        macos: S,
        ios: S,
        android: U,
        gtk4: U,
        windows: U,
        web: U,
        web_name: None,
    },
    Feature {
        name: "perry_system_notification_schedule_interval",
        category: SystemApi,
        macos: S,
        ios: S,
        android: U,
        gtk4: U,
        windows: U,
        web: U,
        web_name: None,
    },
    Feature {
        name: "perry_system_notification_schedule_calendar",
        category: SystemApi,
        macos: S,
        ios: S,
        android: U,
        gtk4: U,
        windows: U,
        web: U,
        web_name: None,
    },
    Feature {
        name: "perry_system_notification_schedule_location",
        category: SystemApi,
        macos: U,
        ios: S,
        android: U,
        gtk4: U,
        windows: U,
        web: U,
        web_name: None,
    },
    Feature {
        name: "perry_system_notification_cancel",
        category: SystemApi,
        macos: S,
        ios: S,
        android: U,
        gtk4: U,
        windows: U,
        web: U,
        web_name: None,
    },
    Feature {
        name: "perry_system_notification_on_tap",
        category: SystemApi,
        macos: S,
        ios: S,
        android: U,
        gtk4: U,
        windows: U,
        web: U,
        web_name: None,
    },
    // ── Web-Only Functions ───────────────────────────────────────────────
    // These exist only in the web runtime and have no native equivalent.
    Feature {
        name: "perry_ui_set_border",
        category: Styling,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_set_frame",
        category: Styling,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_set_on_click",
        category: Events,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_set_opacity",
        category: Styling,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_set_padding",
        category: Styling,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_arc",
        category: Canvas,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_close_path",
        category: Canvas,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_fill",
        category: Canvas,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_fill_rect",
        category: Canvas,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_fill_text",
        category: Canvas,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_draw_image",
        category: Canvas,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_set_fill_color",
        category: Canvas,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_set_font",
        category: Canvas,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_set_line_width",
        category: Canvas,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_set_stroke_color",
        category: Canvas,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_stroke_rect",
        category: Canvas,
        macos: U,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
];
