//! Feature parity rows for widget construction, child management,
//! layout primitives (Layout/ForEach), and visual widgets
//! (Picker/Image/ProgressView).

use crate::{Category::*, Feature, S, U};

pub(crate) const ROWS: &[Feature] = &[
    // ── Widget Creation ──────────────────────────────────────────────────
    Feature {
        name: "perry_ui_text_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_button_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_vstack_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_hstack_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_spacer_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_divider_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_slider_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_toggle_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_textfield_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_securefield_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_scrollview_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_canvas_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_form_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_section_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_zstack_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_lazyvstack_create",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_lazyvstack_update",
        category: WidgetCreation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_table_create",
        category: WidgetCreation,
        macos: S,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_table_set_column_header",
        category: WidgetCreation,
        macos: S,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_table_set_column_width",
        category: WidgetCreation,
        macos: S,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_table_update_row_count",
        category: WidgetCreation,
        macos: S,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_table_set_on_row_select",
        category: WidgetCreation,
        macos: S,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_table_get_selected_row",
        category: WidgetCreation,
        macos: S,
        ios: U,
        android: U,
        gtk4: U,
        windows: U,
        web: S,
        web_name: None,
    },
    // ── Child Management ─────────────────────────────────────────────────
    Feature {
        name: "perry_ui_widget_add_child",
        category: ChildManagement,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_widget_add_child_at",
        category: ChildManagement,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_widget_clear_children",
        category: ChildManagement,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_widget_remove_all_children"),
    },
    // ── Layout ───────────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_vstack_create_with_insets",
        category: Layout,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_hstack_create_with_insets",
        category: Layout,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_stack_set_detaches_hidden",
        category: Layout,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── ForEach ──────────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_for_each_init",
        category: ForEach,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_state_bind_foreach"),
    },
    // ── Picker ───────────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_picker_create",
        category: Picker,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_picker_add_item",
        category: Picker,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_picker_set_selected",
        category: Picker,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_picker_get_selected",
        category: Picker,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── Image ────────────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_image_create_file",
        category: Image,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_image_create"),
    },
    Feature {
        name: "perry_ui_image_create_symbol",
        category: Image,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_load_image",
        category: Image,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_image_set_size",
        category: Image,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_image_set_tint",
        category: Image,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── ProgressView ─────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_progressview_create",
        category: ProgressView,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_progressview_set_value",
        category: ProgressView,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
];
