//! The actual manifest data — the source of truth.
//!
//! Two categories of entry feed this table:
//!
//! 1. **Methods dispatched through `NATIVE_MODULE_TABLE`** in
//!    `crates/perry-codegen/src/lower_call.rs`. These are extracted
//!    mechanically and a CI test in `perry-codegen` asserts that every
//!    `NATIVE_MODULE_TABLE` entry has a counterpart here so drift can't
//!    ship.
//! 2. **Methods/properties dispatched via custom `Expr::*` variants**
//!    in `perry-hir`'s lowering — `crypto.randomUUID` lowers to
//!    `Expr::CryptoRandomUUID` directly, never touching
//!    `NATIVE_MODULE_TABLE`. Same for `os.platform` → `Expr::OsPlatform`,
//!    `path.join` → `Expr::PathJoin`, etc. These are listed manually
//!    below; coverage of a module is what promotes it to "strict mode"
//!    in the unimplemented-API check (#463) — modules with at least
//!    one entry have all references gated against the manifest, modules
//!    with zero entries fall through to existing permissive behavior.
//!
//! Adding a new method/property to a module here automatically lifts
//! the corresponding compile error.

use crate::{ApiEntry, ApiKind, ApiSource};

/// Module specifiers Perry recognizes as native (i.e. resolvable
/// without going through the V8 fallback). Migrated from
/// `crates/perry-hir/src/ir.rs::NATIVE_MODULES` so the manifest can
/// answer module-resolution questions without depending on
/// `perry-hir`. Order matches the original list to keep diffs minimal.
pub const NATIVE_MODULES: &[&str] = &[
    "mysql2",
    "mysql2/promise",
    "pg",
    "uuid",
    "bcrypt",
    "argon2",
    "ioredis",
    "axios",
    "node-fetch",
    "ws",
    "zlib",
    "crypto",
    "dotenv",
    "dotenv/config",
    "jsonwebtoken",
    "nanoid",
    "slugify",
    "validator",
    "ethers",
    "mongodb",
    "better-sqlite3",
    "tursodb",
    "node-cron",
    "nodemailer",
    "http",
    "https",
    "events",
    "os",
    "buffer",
    "child_process",
    "net",
    "tls",
    "stream",
    "fs",
    "path",
    "util",
    "url",
    "lru-cache",
    "commander",
    "decimal.js",
    "bignumber.js",
    "exponential-backoff",
    "lodash",
    "dayjs",
    "moment",
    "sharp",
    "cheerio",
    "cron",
    "fastify",
    "async_hooks",
    "readline",
    "tty",
    "process",
    "perry/tui",
    "perry/ui",
    "perry/system",
    "perry/plugin",
    "perry/widget",
    "perry/i18n",
    "worker_threads",
    "perry/thread",
    "perry/updater",
    "perry/media",
];

/// Modules handled entirely by `perry-runtime` — the linker doesn't
/// need to pull in `perry-stdlib` for these. Migrated from
/// `crates/perry-hir/src/ir.rs::RUNTIME_ONLY_MODULES`.
pub const RUNTIME_ONLY_MODULES: &[&str] = &[
    "fs",
    "path",
    "os",
    "buffer",
    "child_process",
    "stream",
    "url",
    "util",
    "process",
    "perry/ui",
    "perry/system",
    "perry/widget",
    "perry/i18n",
    "perry/thread",
    "perry/media",
    "perry/tui",
    "tty",
];

const fn method(
    module: &'static str,
    name: &'static str,
    has_receiver: bool,
    class_filter: Option<&'static str>,
) -> ApiEntry {
    ApiEntry {
        module,
        name,
        kind: ApiKind::Method {
            has_receiver,
            class_filter,
        },
        source: ApiSource::Stdlib,
        stub: false,
        abi_version: None,
    }
}

const fn property(module: &'static str, name: &'static str) -> ApiEntry {
    ApiEntry {
        module,
        name,
        kind: ApiKind::Property,
        source: ApiSource::Stdlib,
        stub: false,
        abi_version: None,
    }
}

const fn class(module: &'static str, name: &'static str) -> ApiEntry {
    ApiEntry {
        module,
        name,
        kind: ApiKind::Class,
        source: ApiSource::Stdlib,
        stub: false,
        abi_version: None,
    }
}

/// Source-of-truth manifest. See module-level docs for what feeds it.
pub static API_MANIFEST: &[ApiEntry] = &[
    // ===========================================================
    // Methods dispatched via NATIVE_MODULE_TABLE
    // (extracted from crates/perry-codegen/src/lower_call.rs;
    //  drift guarded by perry-codegen's manifest_consistency test)
    // ===========================================================
    method("fastify", "default", false, None),
    method("fastify", "get", true, None),
    method("fastify", "post", true, None),
    method("fastify", "put", true, None),
    method("fastify", "delete", true, None),
    method("fastify", "patch", true, None),
    method("fastify", "head", true, None),
    method("fastify", "options", true, None),
    method("fastify", "all", true, None),
    method("fastify", "route", true, None),
    method("fastify", "addHook", true, None),
    method("fastify", "setErrorHandler", true, None),
    method("fastify", "register", true, None),
    method("fastify", "listen", true, None),
    method("fastify", "method", true, None),
    method("fastify", "url", true, None),
    method("fastify", "params", true, None),
    method("fastify", "param", true, None),
    method("fastify", "query", true, None),
    method("fastify", "rawBody", true, None),
    method("fastify", "headers", true, None),
    method("fastify", "header", true, None),
    method("fastify", "user", true, None),
    method("fastify", "status", true, None),
    method("fastify", "code", true, None),
    method("fastify", "send", true, None),
    method("fastify", "text", true, None),
    method("fastify", "html", true, None),
    method("fastify", "redirect", true, None),
    method("fastify", "json", true, None),
    method("fastify", "body", true, None),
    method("mysql2", "createConnection", false, None),
    method("mysql2", "createPool", false, None),
    method("mysql2/promise", "createConnection", false, None),
    method("mysql2/promise", "createPool", false, None),
    method("mysql2", "query", true, Some("Pool")),
    method("mysql2", "execute", true, Some("Pool")),
    method("mysql2", "end", true, Some("Pool")),
    method("mysql2/promise", "query", true, Some("Pool")),
    method("mysql2/promise", "execute", true, Some("Pool")),
    method("mysql2/promise", "end", true, Some("Pool")),
    method("mysql2", "query", true, Some("PoolConnection")),
    method("mysql2", "execute", true, Some("PoolConnection")),
    method("mysql2/promise", "query", true, Some("PoolConnection")),
    method("mysql2/promise", "execute", true, Some("PoolConnection")),
    method("mysql2", "query", true, None),
    method("mysql2", "execute", true, None),
    method("mysql2", "end", true, None),
    method("mysql2", "getConnection", true, None),
    method("mysql2", "release", true, None),
    method("mysql2", "beginTransaction", true, None),
    method("mysql2", "commit", true, None),
    method("mysql2", "rollback", true, None),
    method("mysql2/promise", "query", true, None),
    method("mysql2/promise", "execute", true, None),
    method("mysql2/promise", "end", true, None),
    method("mysql2/promise", "getConnection", true, None),
    method("mysql2/promise", "release", true, None),
    method("mysql2/promise", "beginTransaction", true, None),
    method("mysql2/promise", "commit", true, None),
    method("mysql2/promise", "rollback", true, None),
    method("pg", "connect", false, None),
    method("pg", "Pool", false, None),
    method("pg", "connect", true, Some("Client")),
    method("pg", "query", true, Some("Pool")),
    method("pg", "end", true, Some("Pool")),
    method("pg", "query", true, None),
    method("pg", "end", true, None),
    method("ioredis", "createClient", false, None),
    method("ioredis", "set", true, None),
    method("ioredis", "get", true, None),
    method("ioredis", "del", true, None),
    method("ioredis", "exists", true, None),
    method("ioredis", "incr", true, None),
    method("ioredis", "decr", true, None),
    method("ioredis", "expire", true, None),
    method("ioredis", "quit", true, None),
    method("mongodb", "connect", false, None),
    method("mongodb", "connect", true, None),
    method("mongodb", "db", true, None),
    method("mongodb", "collection", true, None),
    method("mongodb", "insertOne", true, None),
    method("mongodb", "insertMany", true, None),
    method("mongodb", "find", true, None),
    method("mongodb", "findOne", true, None),
    method("mongodb", "updateOne", true, None),
    method("mongodb", "updateMany", true, None),
    method("mongodb", "deleteOne", true, None),
    method("mongodb", "deleteMany", true, None),
    method("mongodb", "countDocuments", true, None),
    method("mongodb", "close", true, None),
    method("better-sqlite3", "default", false, None),
    method("better-sqlite3", "prepare", true, None),
    method("better-sqlite3", "run", true, None),
    method("better-sqlite3", "get", true, None),
    method("better-sqlite3", "all", true, None),
    method("better-sqlite3", "exec", true, None),
    method("better-sqlite3", "close", true, None),
    // tursodb (#424). MVP surface — open / exec / execBatch /
    // close / lastInsertRowid / isAutocommit. prepare / run /
    // get / all are followups.
    method("tursodb", "open", false, None),
    method("tursodb", "exec", true, None),
    method("tursodb", "execBatch", true, None),
    method("tursodb", "close", true, None),
    method("tursodb", "lastInsertRowid", true, None),
    method("tursodb", "isAutocommit", true, None),
    method("ws", "Server", false, None),
    method("ws", "WebSocket", false, None),
    method("ws", "on", true, None),
    method("ws", "send", true, None),
    method("ws", "close", true, None),
    method("ws", "sendToClient", false, None),
    method("ws", "closeClient", false, None),
    method("net", "createConnection", false, None),
    method("net", "connect", false, None),
    method("net", "Socket", false, None),
    method("net", "connect", true, Some("Socket")),
    method("net", "write", true, Some("Socket")),
    method("net", "end", true, Some("Socket")),
    method("net", "destroy", true, Some("Socket")),
    method("net", "on", true, Some("Socket")),
    method("net", "upgradeToTLS", true, Some("Socket")),
    method("tls", "connect", false, None),
    method("events", "EventEmitter", false, None),
    method("events", "on", true, None),
    method("events", "emit", true, None),
    method("events", "removeListener", true, None),
    method("events", "removeAllListeners", true, None),
    method("lru-cache", "default", false, None),
    method("lru-cache", "get", true, None),
    method("lru-cache", "set", true, None),
    method("lru-cache", "has", true, None),
    method("lru-cache", "delete", true, None),
    method("lru-cache", "clear", true, None),
    method("lru-cache", "size", true, None),
    method("commander", "name", true, None),
    method("commander", "description", true, None),
    method("commander", "version", true, None),
    method("commander", "command", true, None),
    method("commander", "option", true, None),
    method("commander", "requiredOption", true, None),
    method("commander", "action", true, None),
    method("commander", "parse", true, None),
    method("commander", "opts", true, None),
    method("async_hooks", "run", true, None),
    method("async_hooks", "getStore", true, None),
    method("async_hooks", "enterWith", true, None),
    method("async_hooks", "exit", true, None),
    method("async_hooks", "disable", true, None),
    method("decimal.js", "plus", true, None),
    method("decimal.js", "minus", true, None),
    method("decimal.js", "times", true, None),
    method("decimal.js", "div", true, None),
    method("decimal.js", "mod", true, None),
    method("decimal.js", "pow", true, None),
    method("decimal.js", "sqrt", true, None),
    method("decimal.js", "abs", true, None),
    method("decimal.js", "neg", true, None),
    method("decimal.js", "round", true, None),
    method("decimal.js", "floor", true, None),
    method("decimal.js", "ceil", true, None),
    method("decimal.js", "toFixed", true, None),
    method("decimal.js", "toString", true, None),
    method("decimal.js", "toNumber", true, None),
    method("decimal.js", "valueOf", true, None),
    method("decimal.js", "eq", true, None),
    method("decimal.js", "lt", true, None),
    method("decimal.js", "lte", true, None),
    method("decimal.js", "gt", true, None),
    method("decimal.js", "gte", true, None),
    method("decimal.js", "cmp", true, None),
    method("decimal.js", "isZero", true, None),
    method("decimal.js", "isPositive", true, None),
    method("decimal.js", "isNegative", true, None),
    method("uuid", "v4", false, None),
    method("uuid", "v1", false, None),
    method("uuid", "v7", false, None),
    method("uuid", "validate", false, None),
    method("jsonwebtoken", "sign", false, None),
    method("jsonwebtoken", "verify", false, None),
    method("jsonwebtoken", "decode", false, None),
    method("nodemailer", "createTransport", false, None),
    method("nodemailer", "sendMail", true, None),
    method("nodemailer", "verify", true, None),
    method("dotenv", "config", false, None),
    method("nanoid", "nanoid", false, None),
    method("slugify", "default", false, None),
    method("slugify", "slugify", false, None),
    method("validator", "isEmail", false, None),
    method("validator", "isURL", false, None),
    method("validator", "isUUID", false, None),
    method("validator", "isJSON", false, None),
    method("validator", "isEmpty", false, None),
    method("exponential-backoff", "backOff", false, None),
    method("argon2", "hash", false, None),
    method("argon2", "verify", false, None),
    method("bcrypt", "hash", false, None),
    method("bcrypt", "compare", false, None),
    method("perry/thread", "parallelMap", false, None),
    method("perry/thread", "parallelFilter", false, None),
    method("perry/thread", "spawn", false, None),
    method("lodash", "chunk", false, None),
    method("lodash", "compact", false, None),
    method("lodash", "drop", false, None),
    method("lodash", "first", false, None),
    method("lodash", "head", false, None),
    method("lodash", "last", false, None),
    method("lodash", "flatten", false, None),
    method("lodash", "uniq", false, None),
    method("lodash", "reverse", false, None),
    method("lodash", "take", false, None),
    method("lodash", "camelCase", false, None),
    method("lodash", "kebabCase", false, None),
    method("lodash", "snakeCase", false, None),
    method("lodash", "clamp", false, None),
    method("lodash", "range", false, None),
    method("lodash", "times", false, None),
    method("lodash", "size", false, None),
    method("dayjs", "default", false, None),
    method("dayjs", "dayjs", false, None),
    method("dayjs", "format", true, None),
    method("dayjs", "year", true, None),
    method("dayjs", "month", true, None),
    method("dayjs", "date", true, None),
    method("dayjs", "day", true, None),
    method("dayjs", "hour", true, None),
    method("dayjs", "minute", true, None),
    method("dayjs", "second", true, None),
    method("dayjs", "millisecond", true, None),
    method("dayjs", "valueOf", true, None),
    method("dayjs", "unix", true, None),
    method("dayjs", "toISOString", true, None),
    method("dayjs", "add", true, None),
    method("dayjs", "subtract", true, None),
    method("dayjs", "startOf", true, None),
    method("dayjs", "endOf", true, None),
    method("dayjs", "isBefore", true, None),
    method("dayjs", "isAfter", true, None),
    method("dayjs", "isSame", true, None),
    method("dayjs", "isValid", true, None),
    method("dayjs", "diff", true, None),
    method("dayjs", "clone", true, None),
    method("moment", "default", false, None),
    method("moment", "moment", false, None),
    method("sharp", "default", false, None),
    method("sharp", "sharp", false, None),
    method("sharp", "resize", true, None),
    method("sharp", "rotate", true, None),
    method("sharp", "flip", true, None),
    method("sharp", "flop", true, None),
    method("sharp", "grayscale", true, None),
    method("sharp", "blur", true, None),
    method("sharp", "jpeg", true, None),
    method("sharp", "png", true, None),
    method("sharp", "webp", true, None),
    method("sharp", "toFile", true, None),
    method("sharp", "toBuffer", true, None),
    method("sharp", "metadata", true, None),
    method("sharp", "width", true, None),
    method("sharp", "height", true, None),
    method("cheerio", "load", false, None),
    method("cheerio", "select", true, None),
    method("cheerio", "text", true, None),
    method("cheerio", "html", true, None),
    method("cheerio", "attr", true, None),
    method("cheerio", "length", true, None),
    method("cheerio", "first", true, None),
    method("cheerio", "last", true, None),
    method("cheerio", "eq", true, None),
    method("cheerio", "find", true, None),
    method("cheerio", "children", true, None),
    method("cheerio", "parent", true, None),
    method("cheerio", "hasClass", true, None),
    method("zlib", "gzipSync", false, None),
    method("zlib", "gunzipSync", false, None),
    method("zlib", "deflateSync", false, None),
    method("zlib", "inflateSync", false, None),
    method("zlib", "gzip", false, None),
    method("zlib", "gunzip", false, None),
    method("cron", "validate", false, None),
    method("cron", "schedule", false, None),
    method("cron", "describe", false, None),
    method("cron", "start", true, None),
    method("cron", "stop", true, None),
    method("cron", "isRunning", true, None),
    method("cron", "nextDate", true, None),
    method("perry/tui", "Text", false, None),
    method("perry/tui", "Box", false, None),
    method("perry/tui", "render", false, None),
    method("perry/tui", "enter", false, None),
    method("perry/tui", "state", false, None),
    method("perry/tui", "get", true, Some("State")),
    method("perry/tui", "set", true, Some("State")),
    method("perry/tui", "useInput", false, None),
    method("perry/tui", "run", false, None),
    method("perry/tui", "exit", false, None),
    method("perry/tui", "boxSetFlexDirection", false, None),
    method("perry/tui", "boxSetJustifyContent", false, None),
    method("perry/tui", "boxSetAlignItems", false, None),
    method("perry/tui", "boxSetGap", false, None),
    method("perry/tui", "boxSetPadding", false, None),
    method("perry/tui", "boxSetWidth", false, None),
    method("perry/tui", "boxSetHeight", false, None),
    method("perry/tui", "boxSetFlexGrow", false, None),
    method("perry/tui", "Spacer", false, None),
    method("perry/tui", "ProgressBar", false, None),
    method("perry/tui", "Spinner", false, None),
    method("perry/tui", "Input", false, None),
    method("perry/tui", "List", false, None),
    method("perry/tui", "Select", false, None),
    method("perry/tui", "TextArea", false, None),
    method("readline", "createInterface", false, None),
    method("readline", "question", true, None),
    method("readline", "on", true, None),
    method("readline", "close", true, None),
    method("worker_threads", "getWorkerData", false, None),
    method("worker_threads", "workerData", false, None),
    method("worker_threads", "parentPort", false, None),
    method("worker_threads", "postMessage", true, None),
    method("ethers", "getAddress", false, None),
    method("ethers", "formatEther", false, None),
    method("ethers", "formatUnits", false, None),
    method("ethers", "parseEther", false, None),
    method("ethers", "parseUnits", false, None),
    method("ethers", "createRandom", false, Some("Wallet")),
    // ===========================================================
    // Methods dispatched via custom Expr::* variants
    // (perry-hir/src/lower/expr_call.rs and expr_member.rs)
    // ===========================================================

    // crypto — issue #463 calls out crypto.subtle.encrypt as the
    // motivating example. Some entries below are dispatched via
    // codegen-level chain pattern matching (createHash/createHmac via
    // expr.rs:8475+, pbkdf2Sync via expr.rs:8677+) rather than through
    // NATIVE_MODULE_TABLE — they do work, even though they don't show
    // up in the dispatch-table extraction.
    method("crypto", "randomBytes", false, None),
    method("crypto", "randomUUID", false, None),
    method("crypto", "sha256", false, None),
    method("crypto", "md5", false, None),
    method("crypto", "getRandomValues", false, None),
    method("crypto", "createHash", false, None),
    method("crypto", "createHmac", false, None),
    method("crypto", "pbkdf2Sync", false, None),
    method("crypto", "pbkdf2", false, None),
    // os — methods mapped to Expr::Os* in expr_call.rs.
    method("os", "platform", false, None),
    method("os", "arch", false, None),
    method("os", "hostname", false, None),
    method("os", "homedir", false, None),
    method("os", "tmpdir", false, None),
    method("os", "totalmem", false, None),
    method("os", "freemem", false, None),
    method("os", "uptime", false, None),
    method("os", "type", false, None),
    method("os", "release", false, None),
    method("os", "cpus", false, None),
    method("os", "networkInterfaces", false, None),
    method("os", "userInfo", false, None),
    property("os", "EOL"),
    // path — methods mapped to Expr::Path* in expr_call.rs.
    method("path", "join", false, None),
    method("path", "dirname", false, None),
    method("path", "basename", false, None),
    method("path", "extname", false, None),
    method("path", "resolve", false, None),
    method("path", "isAbsolute", false, None),
    method("path", "relative", false, None),
    method("path", "normalize", false, None),
    method("path", "parse", false, None),
    method("path", "format", false, None),
    property("path", "sep"),
    property("path", "delimiter"),
    property("path", "posix"),
    property("path", "win32"),
    // process — properties mapped to Expr::Process* / Expr::Os* in expr_member.rs.
    property("process", "argv"),
    property("process", "platform"),
    property("process", "arch"),
    property("process", "pid"),
    property("process", "ppid"),
    property("process", "version"),
    property("process", "versions"),
    property("process", "stdin"),
    property("process", "stdout"),
    property("process", "stderr"),
    property("process", "env"),
    // ===========================================================
    // Class exports (constructors `new Foo(...)` from a module).
    // ===========================================================
    class("buffer", "Buffer"),
    class("events", "EventEmitter"),
    class("ws", "WebSocketServer"),
    class("ws", "WebSocket"),
    class("net", "Socket"),
    class("net", "Server"),
    class("ioredis", "Redis"),
    class("mysql2/promise", "Pool"),
    class("mysql2", "Pool"),
    class("pg", "Pool"),
    class("pg", "Client"),
    class("url", "URL"),
    class("url", "URLSearchParams"),
];
