use super::*;

pub(super) const EXTRAS_ROWS: &[NativeModSig] = &[
    // ========== worker_threads ==========
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "request",
        class_filter: None,
        runtime: "js_worker_threads_locks_request",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "query",
        class_filter: None,
        runtime: "js_worker_threads_locks_query",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "getEnvironmentData",
        class_filter: None,
        runtime: "js_worker_threads_get_environment_data",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "setEnvironmentData",
        class_filter: None,
        runtime: "js_worker_threads_set_environment_data",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "markAsUntransferable",
        class_filter: None,
        runtime: "js_worker_threads_mark_as_untransferable",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "isMarkedAsUntransferable",
        class_filter: None,
        runtime: "js_worker_threads_is_marked_as_untransferable",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "markAsUncloneable",
        class_filter: None,
        runtime: "js_worker_threads_mark_as_uncloneable",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "moveMessagePortToContext",
        class_filter: None,
        runtime: "js_worker_threads_move_message_port_to_context",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "receiveMessageOnPort",
        class_filter: None,
        runtime: "js_worker_threads_receive_message_on_port",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "postMessageToThread",
        class_filter: None,
        runtime: "js_worker_threads_post_message_to_thread",
        args: &[NA_F64, NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "MessageChannel",
        class_filter: None,
        runtime: "js_worker_threads_message_channel_new",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "BroadcastChannel",
        class_filter: None,
        runtime: "js_worker_threads_broadcast_channel_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // #3899: `workerData` is value-only (not a callable method) — dropping the
    // call routing makes `workerData()` throw a normal TypeError (the value is
    // not a function), matching Node. The value-shaped property arm in
    // `native_module.rs` resolves `workerData` to `null` on the main thread.
    // (`getWorkerData` keeps its routing; see the entries.rs note re: #3896.)
    NativeModSig {
        module: "worker_threads",
        has_receiver: false,
        method: "getWorkerData",
        class_filter: None,
        runtime: "js_worker_threads_get_worker_data",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "postMessage",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_post_message",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "on",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_on",
        args: &[NA_F64, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "once",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_once",
        args: &[NA_F64, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "off",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_off",
        args: &[NA_F64, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "addEventListener",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_add_event_listener",
        args: &[NA_F64, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "removeEventListener",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_remove_event_listener",
        args: &[NA_F64, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "terminate",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_terminate",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "ref",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_ref",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "unref",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_unref",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "getHeapStatistics",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_get_heap_statistics",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "cpuUsage",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_cpu_usage",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "getHeapSnapshot",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_get_heap_snapshot",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "startCpuProfile",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_start_cpu_profile",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "worker_threads",
        has_receiver: true,
        method: "startHeapProfile",
        class_filter: Some("Worker"),
        runtime: "js_worker_threads_worker_start_heap_profile",
        args: &[],
        ret: NR_F64,
    },
    // ========== ethers ==========
    // Utility functions (receiver-less, no class filter).
    NativeModSig {
        module: "ethers",
        has_receiver: false,
        method: "getAddress",
        class_filter: None,
        runtime: "js_ethers_get_address",
        args: &[NA_STR],
        ret: NR_STR,
    },
    NativeModSig {
        module: "ethers",
        has_receiver: false,
        method: "formatEther",
        class_filter: None,
        runtime: "js_ethers_format_ether",
        args: &[NA_PTR],
        ret: NR_STR,
    },
    NativeModSig {
        module: "ethers",
        has_receiver: false,
        method: "formatUnits",
        class_filter: None,
        runtime: "js_ethers_format_units",
        args: &[NA_PTR, NA_F64],
        ret: NR_STR,
    },
    NativeModSig {
        module: "ethers",
        has_receiver: false,
        method: "parseEther",
        class_filter: None,
        runtime: "js_ethers_parse_ether",
        args: &[NA_STR],
        ret: NR_BIGINT,
    },
    NativeModSig {
        module: "ethers",
        has_receiver: false,
        method: "parseUnits",
        class_filter: None,
        runtime: "js_ethers_parse_units",
        args: &[NA_STR, NA_F64],
        ret: NR_BIGINT,
    },
    // Wallet.createRandom() — static method on the Wallet class.
    // class_filter matches `Wallet` so `ethers.Wallet.createRandom()` in
    // HIR (which lowers to class_name="Wallet", method="createRandom")
    // resolves here.
    NativeModSig {
        module: "ethers",
        has_receiver: false,
        method: "createRandom",
        class_filter: Some("Wallet"),
        runtime: "js_ethers_wallet_create_random",
        args: &[],
        ret: NR_PTR,
    },
    // ========== #2875 DisposableStack / AsyncDisposableStack ==========
    // `new DisposableStack()` / `new AsyncDisposableStack()` are dispatched
    // by `lower_builtin_new`; the rows below cover the instance methods and
    // the `disposed` getter. The receiver is NaN-unboxed to a `*mut
    // ObjectHeader` (the stack instance) and passed as the first arg.
    NativeModSig {
        module: "__disposable__",
        has_receiver: true,
        method: "use",
        class_filter: None,
        runtime: "js_disposable_stack_use",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "__disposable__",
        has_receiver: true,
        method: "adopt",
        class_filter: None,
        runtime: "js_disposable_stack_adopt",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "__disposable__",
        has_receiver: true,
        method: "defer",
        class_filter: None,
        runtime: "js_disposable_stack_defer",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "__disposable__",
        has_receiver: true,
        method: "dispose",
        class_filter: None,
        runtime: "js_disposable_stack_dispose",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "__disposable__",
        has_receiver: true,
        method: "disposeAsync",
        class_filter: None,
        runtime: "js_async_disposable_stack_dispose_async",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "__disposable__",
        has_receiver: true,
        method: "move",
        class_filter: None,
        runtime: "js_disposable_stack_move",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "__disposable__",
        has_receiver: true,
        method: "disposed",
        class_filter: None,
        runtime: "js_disposable_stack_disposed",
        args: &[],
        ret: NR_F64,
    },
];
