use super::*;

pub(super) const HTTP_ROWS: &[NativeModSig] = &[
    // ========== node:http / node:https client (issue #769) ==========
    // `http.request(url_or_options, cb)` / `http.get(url_or_options, cb)`
    // and their `https.*` variants. Runtime impls live in
    // `crates/perry-stdlib/src/http.rs` and have been declared in the FFI
    // table for a while, but no `NativeModSig` entries existed — so user
    // code calling `http.request(...)` fell through to the unknown-method
    // path and got back `TAG_UNDEFINED`. Return is a `ClientRequest`
    // handle; the let-stmt arm in `crates/perry-hir/src/lower.rs` tags
    // the binding so `req.on/.end/.write/...` dispatch via the
    // class-filtered entries below.
    // #3226/#3227/#3228 — client factory overloads. Node accepts
    // `request(url[, cb])`, `request(options[, cb])`, and
    // `request(url, options[, cb])` (same for `get`). A fixed
    // `[NA_F64, NA_PTR]` shape mis-routed the options object into the
    // callback slot and dropped the real callback in the three-arg form.
    // Pass every user arg as a JS array (`NA_VARARGS`, mirroring the
    // `listen()` rows) and let the runtime `*_overload` entry points
    // resolve `(url, options, callback)` by value type. Runtime impls
    // live in `crates/perry-ext-http/src/lib.rs`.
    NativeModSig {
        module: "http",
        has_receiver: false,
        method: "request",
        class_filter: None,
        runtime: "js_http_request_overload",
        args: &[NA_VARARGS],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: false,
        method: "get",
        class_filter: None,
        runtime: "js_http_get_overload",
        args: &[NA_VARARGS],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "https",
        has_receiver: false,
        method: "request",
        class_filter: None,
        runtime: "js_https_request_overload",
        args: &[NA_VARARGS],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "https",
        has_receiver: false,
        method: "get",
        class_filter: None,
        runtime: "js_https_get_overload",
        args: &[NA_VARARGS],
        ret: NR_PTR,
    },
    // ClientRequest instance methods (`req.on/.end/.write/.setHeader/.setTimeout`).
    // Shared between `http` and `https` factories — both register the
    // returned binding under module `"http"` in the HIR class table.
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "on",
        class_filter: Some("ClientRequest"),
        runtime: "js_http_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "end",
        class_filter: Some("ClientRequest"),
        runtime: "js_http_client_request_end",
        args: &[NA_F64],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "write",
        class_filter: Some("ClientRequest"),
        runtime: "js_http_client_request_write",
        args: &[NA_F64],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setHeader",
        class_filter: Some("ClientRequest"),
        runtime: "js_http_set_header",
        args: &[NA_STR, NA_STR],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setTimeout",
        class_filter: Some("ClientRequest"),
        runtime: "js_http_set_timeout",
        args: &[NA_F64],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "listenerCount",
        class_filter: Some("ClientRequest"),
        runtime: "js_http_client_request_listener_count",
        args: &[NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_method",
        class_filter: Some("ClientRequest"),
        runtime: "js_http_client_request_method",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_protocol",
        class_filter: Some("ClientRequest"),
        runtime: "js_http_client_request_protocol",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_host",
        class_filter: Some("ClientRequest"),
        runtime: "js_http_client_request_host",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_path",
        class_filter: Some("ClientRequest"),
        runtime: "js_http_client_request_path",
        args: &[],
        ret: NR_STR,
    },
    // ========== http.Agent / https.Agent (issue #2129) ==========
    // `new http.Agent(options?)` / `new https.Agent(options?)` — registered
    // via the Member-callee path in lower/expr_new.rs (mirrors the
    // `new net.Socket()` route). Both classes share the same instance
    // surface; only the constructor differs (default protocol).
    NativeModSig {
        module: "http",
        has_receiver: false,
        method: "Agent",
        class_filter: None,
        runtime: "js_http_agent_new",
        args: &[NA_F64],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "https",
        has_receiver: false,
        method: "Agent",
        class_filter: None,
        runtime: "js_https_agent_new",
        args: &[NA_F64],
        ret: NR_PTR,
    },
    // Agent instance methods. Most are chainable no-ops today — Perry
    // doesn't pool sockets, but Node's test suite asserts the methods
    // exist and don't throw. `getName(options)` is the one method whose
    // exact output the tests check.
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "getName",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_get_name",
        args: &[NA_F64],
        ret: NR_STR,
    },
    // #2154: real `destroy()` flips the `destroyed` flag (no-op
    // pre-#2154 — the agent had nothing to destroy because it owned no
    // sockets). Still chainable: returns the receiver handle.
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "destroy",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_destroy",
        args: &[],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "close",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_noop_self",
        args: &[],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "keepSocketAlive",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_noop_self",
        args: &[],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "reuseSocket",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_noop_self",
        args: &[],
        ret: NR_PTR,
    },
    // Property accessors as `__get_<name>` synthetic methods. The HIR
    // rewrites bare `agent.maxSockets` reads to `agent.__get_maxSockets()`
    // when the receiver is tagged as ("http"|"https", "Agent").
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_maxSockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_max_sockets",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_maxFreeSockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_max_free_sockets",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_maxTotalSockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_max_total_sockets",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_keepAliveMsecs",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_keep_alive_msecs",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_keepAlive",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_keep_alive",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_protocol",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_protocol",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_defaultPort",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_default_port",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_protocol",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_set_protocol",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    // Bare-name dispatch for the same property reads. Mirrors the
    // belt-and-braces approach used by IncomingMessage's `statusCode` /
    // `headers` rows below — covers sites where the HIR rewrite to
    // `__get_<prop>` doesn't fire (e.g. an agent assigned through a
    // local before the property read).
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "maxSockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_max_sockets",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "maxFreeSockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_max_free_sockets",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "maxTotalSockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_max_total_sockets",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "keepAliveMsecs",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_keep_alive_msecs",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "keepAlive",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_keep_alive",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "protocol",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_protocol",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "defaultPort",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_default_port",
        args: &[],
        ret: NR_F64,
    },
    // ========== http.Agent / https.Agent (issue #2154) ==========
    // Extra surface the #2129 first PR didn't cover: sockets /
    // freeSockets / requests accessors (return empty objects),
    // destroyed getter + destroy(), tunable property setters with
    // RangeError-throwing validation, and createConnection /
    // createSocket override storage.
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_sockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_sockets",
        args: &[],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "sockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_sockets",
        args: &[],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_freeSockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_free_sockets",
        args: &[],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "freeSockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_free_sockets",
        args: &[],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_requests",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_requests",
        args: &[],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "requests",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_requests",
        args: &[],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_destroyed",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_destroyed",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "destroyed",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_destroyed",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_maxSockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_set_max_sockets",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_maxFreeSockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_set_max_free_sockets",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_maxTotalSockets",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_set_max_total_sockets",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_keepAlive",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_set_keep_alive",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_keepAliveMsecs",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_set_keep_alive_msecs",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_createConnection",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_set_create_connection",
        args: &[NA_PTR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_createSocket",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_set_create_socket",
        args: &[NA_PTR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_createConnection",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_create_connection",
        args: &[],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_createSocket",
        class_filter: Some("Agent"),
        runtime: "js_http_agent_create_socket",
        args: &[],
        ret: NR_PTR,
    },
    // ========== node:http server (issue #577) ==========
    // Module-level: `import { createServer } from "node:http"; createServer(handler)`
    // Issue #2210 — accepts an optional 2nd `options` arg (Node 18.4+):
    //   `createServer(handler, { headersTimeout, keepAliveTimeout, ... })`
    // The runtime distinguishes the no-args / handler-only / handler+opts
    // cases by the JsValue tag on the second arg (UNDEFINED vs pointer);
    // a 0-arg call leaves both NA_PTR / NA_JSV slots as `undefined`.
    NativeModSig {
        module: "http",
        has_receiver: false,
        method: "createServer",
        class_filter: None,
        runtime: "js_node_http_create_server_with_options",
        args: &[NA_PTR, NA_JSV],
        ret: NR_PTR,
    },
    // `http.Server(handler)` is Node's callable-constructor alias for
    // `http.createServer` (works with or without `new`). #2132.
    // Same `(handler, options?)` shape as `createServer` above (#2210).
    NativeModSig {
        module: "http",
        has_receiver: false,
        method: "Server",
        class_filter: None,
        runtime: "js_node_http_create_server_with_options",
        args: &[NA_PTR, NA_JSV],
        ret: NR_PTR,
    },
    // HttpServer instance methods (class_filter: HttpServer)
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "listen",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_listen",
        // Node's `listen()` is variadic: listen(port[, host][, backlog][, cb]),
        // listen(options[, cb]), listen(cb). Positional NativeArgKinds can't
        // express "the callback floats to whichever position it's in", so pass
        // every user arg as a JS array and let the runtime resolve the overload
        // by value type (string→host, function→callback). Pre-#2041 the fixed
        // `[NA_F64, NA_PTR]` mis-routed a host string into the callback slot and
        // dropped the real callback. Issue #2041.
        //
        // #2129: returns the server handle (NR_PTR) so
        // `createServer(...).listen(...).on(...)` chains correctly. Pre-fix
        // this was NR_VOID and chained sites broke at runtime with
        // `undefined.on is not a function`.
        args: &[NA_VARARGS],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "close",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_close",
        args: &[NA_PTR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "closeAllConnections",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_close_all_connections",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "closeIdleConnections",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_close_idle_connections",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "on",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "addListener",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    // `server.address()` — returns `{ port, address, family }` (or `null`
    // before listen completes). Runtime serializes to JSON; codegen
    // parses via `NR_OBJ_FROM_JSON_STR`. Without this row, `server.address()`
    // fell through to typed-feedback dispatch and returned NaN.
    // (#2153 followup to #2129.)
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "address",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_address_json",
        args: &[],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    // Issue #2210 — `server.<name>` timeout / socket-option accessors.
    // The HIR rewrites `server.headersTimeout` reads / writes to
    // `__get_headersTimeout` / `__set_headersTimeout` synthetic methods
    // when the receiver is tagged as `("http", "HttpServer")`; bare-name
    // fallback rows also wired so receivers that escape the HIR-rewrite
    // (e.g. assigned through a local before the property access) still
    // hit the FFI.
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_headersTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_headers_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_headersTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_headers_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_keepAliveTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_keep_alive_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_keepAliveTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_keep_alive_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_requestTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_request_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_requestTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_request_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_timeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_idle_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_timeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_idle_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_maxHeadersCount",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_max_headers_count",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_maxHeadersCount",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_max_headers_count",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_maxRequestsPerSocket",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_max_requests_per_socket",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_maxRequestsPerSocket",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_max_requests_per_socket",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // Bare-name dispatch — same FFI, covers receivers that escape the
    // `__get_<name>` HIR rewrite (e.g. assigned through a local).
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "headersTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_headers_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "keepAliveTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_keep_alive_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "requestTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_request_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "timeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_idle_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "maxHeadersCount",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_max_headers_count",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "maxRequestsPerSocket",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_max_requests_per_socket",
        args: &[],
        ret: NR_F64,
    },
    // `server.setTimeout(msecs, [callback])` — the canonical
    // EventEmitter-style setter mirrors `socket.setTimeout`. The
    // callback (if supplied) is registered as a `'timeout'` listener.
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_timeout_method",
        args: &[NA_F64, NA_PTR],
        ret: NR_PTR,
    },
    // IncomingMessage instance methods
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "on",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "addListener",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "pause",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_pause",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "resume",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_resume",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "destroy",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_destroy",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "read",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_read",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setEncoding",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_incoming_message_set_encoding",
        args: &[NA_STR],
        ret: NR_PTR,
    },
    // ServerResponse instance methods
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setHeader",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_set_header",
        args: &[NA_STR, NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "getHeader",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_get_header",
        args: &[NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "removeHeader",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_remove_header",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "hasHeader",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_has_header",
        args: &[NA_STR],
        ret: NR_I32,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "writeHead",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_write_head",
        // #2132: arg2/arg3 are raw JSValues so the runtime can disambiguate
        // the `writeHead(status, headers)` vs `writeHead(status, statusMessage,
        // headers)` overloads (string ⇒ statusMessage, object ⇒ headers) and
        // serialize the headers object. Previously typed `NA_STR`, which
        // coerced a headers *object* to `"[object Object]"` and silently
        // dropped every header passed via `writeHead`.
        args: &[NA_F64, NA_JSV, NA_JSV],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "write",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_write",
        args: &[NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "addTrailers",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_add_trailers",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "end",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_end",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "flushHeaders",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_flush_headers",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "writeContinue",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_write_continue",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "writeProcessing",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_write_processing",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "on",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "addListener",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    // Method-call aliases for property-style accessors. Until the
    // HIR-level PropertyGet→__get_<name> rewrite lands (followup),
    // user code must use the method-call form: `req.method()` (calls
    // js_node_http_im_method) instead of `req.method` (property
    // read). Same shape as fastify's `request.method()` / `request.url()`.
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "method",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_method",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "url",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_url",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "httpVersion",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_http_version",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setStatus",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_set_status",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "getStatus",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_get_status",
        args: &[],
        ret: NR_F64,
    },
    // Property accessors as `__get_<name>` / `__set_<name>` synthetic methods
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_method",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_method",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_url",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_url",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_httpVersion",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_http_version",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_complete",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_complete",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_aborted",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_aborted",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_destroyed",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_destroyed",
        args: &[],
        ret: NR_I32,
    },
    // Closes #769 followup — client-side `res.statusCode` /
    // `res.statusMessage` / `res.headers` after `http.request(url, cb)`.
    // The HIR registers the `res` arrow param as ("http",
    // "IncomingMessage"); these entries route the rewritten
    // `__get_<prop>` reads to perry-ext-http's accessor (the same
    // crate that owns the client-IncomingMessage registry the
    // response queue populates). (Restored after the #1099 squash-merge
    // dropped them via a conflict auto-resolution.)
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_statusCode",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_status_code",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_statusMessage",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_status_message",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_headers",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_response_headers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_trailers",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_response_trailers",
        args: &[],
        ret: NR_F64,
    },
    // PR #1146 belt-and-braces: bare-name dispatch for the same three
    // client-IncomingMessage properties, for sites where the HIR rewrite
    // to `__get_<prop>` doesn't fire (receiver isn't statically tagged
    // as ("http", "IncomingMessage"), e.g. one assigned through a local
    // before the property read).
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "statusCode",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_status_code",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "statusMessage",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_status_message",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "headers",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_response_headers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "trailers",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_response_trailers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_statusCode",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_get_status",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_statusCode",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_set_status",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_statusMessage",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_set_status_message",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_headersSent",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_headers_sent",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_writableEnded",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_writable_ended",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_writableFinished",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_writable_finished",
        args: &[],
        ret: NR_I32,
    },
    // ========== node:https server (issue #577 Phase 2) ==========
    NativeModSig {
        module: "https",
        has_receiver: false,
        method: "createServer",
        class_filter: None,
        runtime: "js_node_https_create_server",
        args: &[NA_F64, NA_PTR],
        ret: NR_PTR,
    },
    // `https.Server(options, handler)` is Node's callable-constructor
    // alias for `https.createServer` (works with or without `new`). #2132.
    NativeModSig {
        module: "https",
        has_receiver: false,
        method: "Server",
        class_filter: None,
        runtime: "js_node_https_create_server",
        args: &[NA_F64, NA_PTR],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "listen",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_listen",
        // Variadic listen() overloads — see the http `listen` row. Issue #2041.
        // Returns the server handle for chainability (#2129).
        args: &[NA_VARARGS],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "close",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_close",
        args: &[NA_PTR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "on",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "addListener",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "address",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_address_json",
        args: &[],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "closeAllConnections",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_close_all_connections",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "closeIdleConnections",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_close_idle_connections",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_headersTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_headers_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_headersTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_headers_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_keepAliveTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_keep_alive_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_keepAliveTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_keep_alive_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_requestTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_request_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_requestTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_request_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_timeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_idle_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_timeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_idle_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_maxHeadersCount",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_max_headers_count",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_maxHeadersCount",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_max_headers_count",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_maxRequestsPerSocket",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_max_requests_per_socket",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_maxRequestsPerSocket",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_max_requests_per_socket",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "headersTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_headers_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "keepAliveTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_keep_alive_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "requestTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_request_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "timeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_idle_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "maxHeadersCount",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_max_headers_count",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "maxRequestsPerSocket",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_max_requests_per_socket",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "setTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_timeout_method",
        args: &[NA_F64, NA_PTR],
        ret: NR_PTR,
    },
    // ========== node:http2 server (issue #577 Phase 3) ==========
    NativeModSig {
        module: "http2",
        has_receiver: false,
        method: "createSecureServer",
        class_filter: None,
        runtime: "js_node_http2_create_secure_server",
        args: &[NA_F64, NA_PTR],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http2",
        has_receiver: true,
        method: "listen",
        class_filter: Some("Http2SecureServer"),
        runtime: "js_node_http2_server_listen",
        // Variadic listen() overloads — see the http `listen` row. Issue #2041.
        // Returns the server handle for chainability (#2129).
        args: &[NA_VARARGS],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http2",
        has_receiver: true,
        method: "close",
        class_filter: Some("Http2SecureServer"),
        runtime: "js_node_http2_server_close",
        args: &[NA_PTR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http2",
        has_receiver: true,
        method: "on",
        class_filter: Some("Http2SecureServer"),
        runtime: "js_node_http2_server_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http2",
        has_receiver: true,
        method: "address",
        class_filter: Some("Http2SecureServer"),
        runtime: "js_node_http2_server_address_json",
        args: &[],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    // ========== node:http2 settings helpers (issue #3168) ==========
    // Pure pack/unpack functions implemented in perry-ext-http-server (so
    // their Buffer alloc/recognition shares the program's runtime copy).
    NativeModSig {
        module: "http2",
        has_receiver: false,
        method: "getDefaultSettings",
        class_filter: None,
        runtime: "js_node_http2_get_default_settings",
        args: &[],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    NativeModSig {
        module: "http2",
        has_receiver: false,
        method: "getPackedSettings",
        class_filter: None,
        runtime: "js_node_http2_get_packed_settings",
        // NA_JSV: pass the settings object's raw NaN-boxed bits (the runtime
        // JSON-stringifies it); NR_PTR: return value is a Buffer pointer.
        args: &[NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "http2",
        has_receiver: false,
        method: "getUnpackedSettings",
        class_filter: None,
        runtime: "js_node_http2_get_unpacked_settings",
        // NA_JSV: pass the Buffer's raw bits (runtime reads it via the
        // buffer-registry shim); NR_OBJ_FROM_JSON_STR: returns a settings
        // object reparsed from JSON.
        args: &[NA_JSV],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    // `@perryts/google-auth` is no longer bundled in perry-stdlib —
    // since v0.5.1015 the package is published as a standalone npm
    // module (https://github.com/PerryTS/google-auth). Codegen
    // dispatches `js_google_auth_*` symbols through `ffi_signatures`
    // built from the installed package's
    // `perry.nativeLibrary.functions`, same as any other external
    // nativeLibrary crate.
    // ========== perry/ads (issue #867) ==========
    // Six FFI entry points exported by `crates/perry-ext-ads`:
    //   - 4 promise-returning load/show pairs for interstitial +
    //     rewarded (NR_PROMISE — runtime sees a `*mut perry_ffi::Promise`
    //     and NaN-boxes via an explicit promise-boundary transition).
    //   - 2 synchronous banner create/destroy (NR_F64 / NR_VOID —
    //     banner_create returns a handle as a `number`, destroy is
    //     fire-and-forget).
    // MVP returns structured `{ error: "no-sdk-linked" }`
    // placeholders; real Google Mobile Ads SDK integration follows.
    NativeModSig {
        module: "perry/ads",
        has_receiver: false,
        method: "js_ads_interstitial_load",
        class_filter: None,
        runtime: "js_ads_interstitial_load",
        args: &[NA_STR],
        ret: NR_PROMISE,
    },
    NativeModSig {
        module: "perry/ads",
        has_receiver: false,
        method: "js_ads_interstitial_show",
        class_filter: None,
        runtime: "js_ads_interstitial_show",
        args: &[],
        ret: NR_PROMISE,
    },
    NativeModSig {
        module: "perry/ads",
        has_receiver: false,
        method: "js_ads_rewarded_load",
        class_filter: None,
        runtime: "js_ads_rewarded_load",
        args: &[NA_STR],
        ret: NR_PROMISE,
    },
    NativeModSig {
        module: "perry/ads",
        has_receiver: false,
        method: "js_ads_rewarded_show",
        class_filter: None,
        runtime: "js_ads_rewarded_show",
        args: &[],
        ret: NR_PROMISE,
    },
    NativeModSig {
        module: "perry/ads",
        has_receiver: false,
        method: "js_ads_banner_create",
        class_filter: None,
        runtime: "js_ads_banner_create",
        args: &[NA_STR, NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "perry/ads",
        has_receiver: false,
        method: "js_ads_banner_destroy",
        class_filter: None,
        runtime: "js_ads_banner_destroy",
        args: &[NA_F64],
        ret: NR_VOID,
    },
];
