use super::*;

/// Native-table rows for the `node:v8` module (#3137/#3138/#3142):
/// serialize/deserialize, heap statistics, `cachedDataVersionTag`, and the
/// `Serializer`/`Deserializer` class surface. Extracted from node_core.rs to
/// keep that file under the 2000-line CI gate.
pub(super) const NODE_V8_ROWS: &[NativeModSig] = &[
    // ========== Node v8 ==========
    NativeModSig {
        module: "v8",
        has_receiver: false,
        method: "serialize",
        class_filter: None,
        runtime: "js_v8_serialize",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: false,
        method: "deserialize",
        class_filter: None,
        runtime: "js_v8_deserialize",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: false,
        method: "cachedDataVersionTag",
        class_filter: None,
        runtime: "js_v8_cached_data_version_tag",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: false,
        method: "getHeapStatistics",
        class_filter: None,
        runtime: "js_v8_get_heap_statistics",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: false,
        method: "getHeapCodeStatistics",
        class_filter: None,
        runtime: "js_v8_get_heap_code_statistics",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: false,
        method: "getHeapSpaceStatistics",
        class_filter: None,
        runtime: "js_v8_get_heap_space_statistics",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: false,
        method: "Serializer",
        class_filter: None,
        runtime: "js_v8_serializer_new",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: false,
        method: "DefaultSerializer",
        class_filter: None,
        runtime: "js_v8_default_serializer_new",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: false,
        method: "Deserializer",
        class_filter: None,
        runtime: "js_v8_deserializer_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: false,
        method: "DefaultDeserializer",
        class_filter: None,
        runtime: "js_v8_default_deserializer_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "writeHeader",
        class_filter: Some("Serializer"),
        runtime: "js_v8_serializer_write_header",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "writeHeader",
        class_filter: Some("DefaultSerializer"),
        runtime: "js_v8_serializer_write_header",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "writeValue",
        class_filter: Some("Serializer"),
        runtime: "js_v8_serializer_write_value",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "writeValue",
        class_filter: Some("DefaultSerializer"),
        runtime: "js_v8_serializer_write_value",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "releaseBuffer",
        class_filter: Some("Serializer"),
        runtime: "js_v8_serializer_release_buffer",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "releaseBuffer",
        class_filter: Some("DefaultSerializer"),
        runtime: "js_v8_serializer_release_buffer",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "transferArrayBuffer",
        class_filter: Some("Serializer"),
        runtime: "js_v8_serializer_transfer_array_buffer",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "transferArrayBuffer",
        class_filter: Some("DefaultSerializer"),
        runtime: "js_v8_serializer_transfer_array_buffer",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "writeUint32",
        class_filter: Some("Serializer"),
        runtime: "js_v8_serializer_write_uint32",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "writeUint32",
        class_filter: Some("DefaultSerializer"),
        runtime: "js_v8_serializer_write_uint32",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "writeUint64",
        class_filter: Some("Serializer"),
        runtime: "js_v8_serializer_write_uint64",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "writeUint64",
        class_filter: Some("DefaultSerializer"),
        runtime: "js_v8_serializer_write_uint64",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "writeDouble",
        class_filter: Some("Serializer"),
        runtime: "js_v8_serializer_write_double",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "writeDouble",
        class_filter: Some("DefaultSerializer"),
        runtime: "js_v8_serializer_write_double",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "writeRawBytes",
        class_filter: Some("Serializer"),
        runtime: "js_v8_serializer_write_raw_bytes",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "writeRawBytes",
        class_filter: Some("DefaultSerializer"),
        runtime: "js_v8_serializer_write_raw_bytes",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "_getDataCloneError",
        class_filter: Some("Serializer"),
        runtime: "js_v8_serializer_get_data_clone_error",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "_getDataCloneError",
        class_filter: Some("DefaultSerializer"),
        runtime: "js_v8_serializer_get_data_clone_error",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "_setTreatArrayBufferViewsAsHostObjects",
        class_filter: Some("Serializer"),
        runtime: "js_v8_serializer_set_treat_array_buffer_views_as_host_objects",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "_setTreatArrayBufferViewsAsHostObjects",
        class_filter: Some("DefaultSerializer"),
        runtime: "js_v8_serializer_set_treat_array_buffer_views_as_host_objects",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "readHeader",
        class_filter: Some("Deserializer"),
        runtime: "js_v8_deserializer_read_header",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "readHeader",
        class_filter: Some("DefaultDeserializer"),
        runtime: "js_v8_deserializer_read_header",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "readValue",
        class_filter: Some("Deserializer"),
        runtime: "js_v8_deserializer_read_value",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "readValue",
        class_filter: Some("DefaultDeserializer"),
        runtime: "js_v8_deserializer_read_value",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "getWireFormatVersion",
        class_filter: Some("Deserializer"),
        runtime: "js_v8_deserializer_get_wire_format_version",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "getWireFormatVersion",
        class_filter: Some("DefaultDeserializer"),
        runtime: "js_v8_deserializer_get_wire_format_version",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "transferArrayBuffer",
        class_filter: Some("Deserializer"),
        runtime: "js_v8_deserializer_transfer_array_buffer",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "transferArrayBuffer",
        class_filter: Some("DefaultDeserializer"),
        runtime: "js_v8_deserializer_transfer_array_buffer",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "readUint32",
        class_filter: Some("Deserializer"),
        runtime: "js_v8_deserializer_read_uint32",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "readUint32",
        class_filter: Some("DefaultDeserializer"),
        runtime: "js_v8_deserializer_read_uint32",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "readUint64",
        class_filter: Some("Deserializer"),
        runtime: "js_v8_deserializer_read_uint64",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "readUint64",
        class_filter: Some("DefaultDeserializer"),
        runtime: "js_v8_deserializer_read_uint64",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "readDouble",
        class_filter: Some("Deserializer"),
        runtime: "js_v8_deserializer_read_double",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "readDouble",
        class_filter: Some("DefaultDeserializer"),
        runtime: "js_v8_deserializer_read_double",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "readRawBytes",
        class_filter: Some("Deserializer"),
        runtime: "js_v8_deserializer_read_raw_bytes",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "v8",
        has_receiver: true,
        method: "readRawBytes",
        class_filter: Some("DefaultDeserializer"),
        runtime: "js_v8_deserializer_read_raw_bytes",
        args: &[NA_F64],
        ret: NR_F64,
    },
];
