use super::*;

pub(super) const NODE_CORE_ROWS: &[NativeModSig] = &[
    // ========== Node module ==========
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "isBuiltin",
        class_filter: None,
        runtime: "js_module_is_builtin",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "SourceMap",
        class_filter: None,
        runtime: "js_module_source_map_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node TTY ==========
    NativeModSig {
        module: "tty",
        has_receiver: false,
        method: "isatty",
        class_filter: None,
        runtime: "js_tty_isatty",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node OS ==========
    NativeModSig {
        module: "os",
        has_receiver: false,
        method: "getPriority",
        class_filter: None,
        runtime: "js_os_get_priority",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "os",
        has_receiver: false,
        method: "setPriority",
        class_filter: None,
        runtime: "js_os_set_priority",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // ========== Node process EventEmitter ==========
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "on",
        class_filter: None,
        runtime: "js_process_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "addListener",
        class_filter: None,
        runtime: "js_process_add_listener",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "once",
        class_filter: None,
        runtime: "js_process_once",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "prependListener",
        class_filter: None,
        runtime: "js_process_prepend_listener",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "prependOnceListener",
        class_filter: None,
        runtime: "js_process_prepend_once_listener",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "emit",
        class_filter: None,
        runtime: "js_process_emit",
        args: &[NA_STR, NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "removeListener",
        class_filter: None,
        runtime: "js_process_remove_listener",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "off",
        class_filter: None,
        runtime: "js_process_off",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "removeAllListeners",
        class_filter: None,
        runtime: "js_process_remove_all_listeners",
        args: &[NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "listenerCount",
        class_filter: None,
        runtime: "js_process_listener_count",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "listeners",
        class_filter: None,
        runtime: "js_process_listeners",
        args: &[NA_STR],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "rawListeners",
        class_filter: None,
        runtime: "js_process_raw_listeners",
        args: &[NA_STR],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "eventNames",
        class_filter: None,
        runtime: "js_process_event_names",
        args: &[],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setMaxListeners",
        class_filter: None,
        runtime: "js_process_set_max_listeners",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "getMaxListeners",
        class_filter: None,
        runtime: "js_process_get_max_listeners",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "getBuiltinModule",
        class_filter: None,
        runtime: "js_process_get_builtin_module",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // #2135 (Node process parity): process.loadEnvFile(path?) — HIR
    // defaults the missing path to ".env" so this row always sees a
    // single string argument.
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "loadEnvFile",
        class_filter: None,
        runtime: "js_process_load_env_file",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    // #2135 (Node process parity): process.getgroups() — Array<number>
    // of supplementary GIDs from libc::getgroups (empty on non-unix).
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "getgroups",
        class_filter: None,
        runtime: "js_process_getgroups",
        args: &[],
        ret: NR_F64,
    },
    // #2135 (Node process parity): POSIX credential setters — single
    // numeric ID arg, void return.
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setuid",
        class_filter: None,
        runtime: "js_process_setuid",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "seteuid",
        class_filter: None,
        runtime: "js_process_seteuid",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setgid",
        class_filter: None,
        runtime: "js_process_setgid",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setegid",
        class_filter: None,
        runtime: "js_process_setegid",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    // #2135: process.setgroups(groups[]) — JSValue array of numeric GIDs.
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setgroups",
        class_filter: None,
        runtime: "js_process_setgroups",
        args: &[NA_JSV],
        ret: NR_VOID,
    },
    // #2135: process.initgroups(user, extra_gid) — username + numeric GID.
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "initgroups",
        class_filter: None,
        runtime: "js_process_initgroups",
        args: &[NA_JSV, NA_F64],
        ret: NR_VOID,
    },
    // ========== Node URL ==========
    // `new Number/String/Boolean(...)` now lowers to
    // `Expr::BoxedPrimitiveNew` (see crates/perry-hir/src/lower/expr_new.rs)
    // and is emitted by codegen as a direct runtime call — no dispatch
    // table row needed.
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "fileURLToPath",
        class_filter: None,
        runtime: "js_url_file_url_to_path",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "fileURLToPathBuffer",
        class_filter: None,
        runtime: "js_url_file_url_to_path_buffer",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "pathToFileURL",
        class_filter: None,
        runtime: "js_url_path_to_file_url",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "domainToASCII",
        class_filter: None,
        runtime: "js_url_domain_to_ascii",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "domainToUnicode",
        class_filter: None,
        runtime: "js_url_domain_to_unicode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "urlToHttpOptions",
        class_filter: None,
        runtime: "js_url_to_http_options",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "format",
        class_filter: None,
        runtime: "js_url_format",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "parse",
        class_filter: None,
        runtime: "js_url_legacy_parse",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "resolve",
        class_filter: None,
        runtime: "js_url_legacy_resolve",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // ========== Node punycode (deprecated, #2513) ==========
    NativeModSig {
        module: "punycode",
        has_receiver: false,
        method: "decode",
        class_filter: None,
        runtime: "js_punycode_decode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "punycode",
        has_receiver: false,
        method: "encode",
        class_filter: None,
        runtime: "js_punycode_encode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "punycode",
        has_receiver: false,
        method: "toASCII",
        class_filter: None,
        runtime: "js_punycode_to_ascii",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "punycode",
        has_receiver: false,
        method: "toUnicode",
        class_filter: None,
        runtime: "js_punycode_to_unicode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // punycode.ucs2 sub-namespace (#2607): decode(string)->code-point array,
    // encode(code-point array)->string. The array arg/return ride as a
    // NaN-boxed pointer in the NA_F64 slot.
    NativeModSig {
        module: "punycode.ucs2",
        has_receiver: false,
        method: "decode",
        class_filter: None,
        runtime: "js_punycode_ucs2_decode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "punycode.ucs2",
        has_receiver: false,
        method: "encode",
        class_filter: None,
        runtime: "js_punycode_ucs2_encode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node console ==========
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "log",
        class_filter: None,
        runtime: "js_console_log_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "info",
        class_filter: None,
        runtime: "js_console_info_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "debug",
        class_filter: None,
        runtime: "js_console_debug_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "dirxml",
        class_filter: None,
        runtime: "js_console_log_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "error",
        class_filter: None,
        runtime: "js_console_error_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "warn",
        class_filter: None,
        runtime: "js_console_warn_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "assert",
        class_filter: None,
        runtime: "js_console_assert_spread",
        args: &[NA_F64, NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "dir",
        class_filter: None,
        runtime: "js_console_log_dynamic",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "trace",
        class_filter: None,
        runtime: "js_console_trace",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "table",
        class_filter: None,
        runtime: "js_console_table",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "clear",
        class_filter: None,
        runtime: "js_console_clear",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "count",
        class_filter: None,
        runtime: "js_console_count",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "countReset",
        class_filter: None,
        runtime: "js_console_count_reset",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "time",
        class_filter: None,
        runtime: "js_console_time",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "timeEnd",
        class_filter: None,
        runtime: "js_console_time_end",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "timeLog",
        class_filter: None,
        runtime: "js_console_time_log",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "groupEnd",
        class_filter: None,
        runtime: "js_console_group_end",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "group",
        class_filter: None,
        runtime: "js_console_group_begin",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "groupCollapsed",
        class_filter: None,
        runtime: "js_console_group_begin",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "profile",
        class_filter: None,
        runtime: "js_console_noop",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "profileEnd",
        class_filter: None,
        runtime: "js_console_noop",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "timeStamp",
        class_filter: None,
        runtime: "js_console_noop",
        args: &[],
        ret: NR_VOID,
    },
    // ========== Node assert ==========
    // Root-callable `assert(value, message?)` — HIR lowers
    // `import assert from "node:assert"; assert(x, m)` to a
    // `NativeMethodCall { module: "assert", method: "default" }`.
    // Route it to `js_assert_ok` (Node's default export aliases
    // `assert.ok`). Same for `node:assert/strict`.
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "default",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "default",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // `assert.strict(value, msg?)` — the `.strict` namespace itself is
    // callable and behaves like `assert.strict.ok`.
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "strict",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "strict",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "ok",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "fail",
        class_filter: None,
        runtime: "js_assert_fail",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "equal",
        class_filter: None,
        runtime: "js_assert_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "notEqual",
        class_filter: None,
        runtime: "js_assert_not_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "strictEqual",
        class_filter: None,
        runtime: "js_assert_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "notStrictEqual",
        class_filter: None,
        runtime: "js_assert_not_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "deepEqual",
        class_filter: None,
        runtime: "js_assert_deep_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "notDeepEqual",
        class_filter: None,
        runtime: "js_assert_not_deep_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "deepStrictEqual",
        class_filter: None,
        runtime: "js_assert_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "partialDeepStrictEqual",
        class_filter: None,
        runtime: "js_assert_partial_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "notDeepStrictEqual",
        class_filter: None,
        runtime: "js_assert_not_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "match",
        class_filter: None,
        runtime: "js_assert_match",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "doesNotMatch",
        class_filter: None,
        runtime: "js_assert_does_not_match",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "throws",
        class_filter: None,
        runtime: "js_assert_throws",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "doesNotThrow",
        class_filter: None,
        runtime: "js_assert_does_not_throw",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "rejects",
        class_filter: None,
        runtime: "js_assert_rejects",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "doesNotReject",
        class_filter: None,
        runtime: "js_assert_does_not_reject",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "ifError",
        class_filter: None,
        runtime: "js_assert_if_error",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "ok",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "fail",
        class_filter: None,
        runtime: "js_assert_fail",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "equal",
        class_filter: None,
        runtime: "js_assert_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "notEqual",
        class_filter: None,
        runtime: "js_assert_not_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "deepEqual",
        class_filter: None,
        runtime: "js_assert_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "notDeepEqual",
        class_filter: None,
        runtime: "js_assert_not_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "strictEqual",
        class_filter: None,
        runtime: "js_assert_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "notStrictEqual",
        class_filter: None,
        runtime: "js_assert_not_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "deepStrictEqual",
        class_filter: None,
        runtime: "js_assert_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "partialDeepStrictEqual",
        class_filter: None,
        runtime: "js_assert_partial_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "notDeepStrictEqual",
        class_filter: None,
        runtime: "js_assert_not_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "match",
        class_filter: None,
        runtime: "js_assert_match",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "doesNotMatch",
        class_filter: None,
        runtime: "js_assert_does_not_match",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "throws",
        class_filter: None,
        runtime: "js_assert_throws",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "doesNotThrow",
        class_filter: None,
        runtime: "js_assert_does_not_throw",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "rejects",
        class_filter: None,
        runtime: "js_assert_rejects",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "doesNotReject",
        class_filter: None,
        runtime: "js_assert_does_not_reject",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "ifError",
        class_filter: None,
        runtime: "js_assert_if_error",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node util ==========
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "inspect",
        class_filter: None,
        runtime: "js_util_inspect",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "convertProcessSignalToExitCode",
        class_filter: None,
        runtime: "js_util_convert_process_signal_to_exit_code",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "isArray",
        class_filter: None,
        runtime: "js_array_is_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "isDeepStrictEqual",
        class_filter: None,
        runtime: "js_util_is_deep_strict_equal",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "stripVTControlCharacters",
        class_filter: None,
        runtime: "js_util_strip_vt_control_characters",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "styleText",
        class_filter: None,
        runtime: "js_util_style_text",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    // #2514: util.getSystemErrorName/Message(errno) + getSystemErrorMap().
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "getSystemErrorName",
        class_filter: None,
        runtime: "js_util_get_system_error_name",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "getSystemErrorMessage",
        class_filter: None,
        runtime: "js_util_get_system_error_message",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "getSystemErrorMap",
        class_filter: None,
        runtime: "js_util_get_system_error_map",
        args: &[],
        ret: NR_F64,
    },
    // #2514: util.parseEnv(content) → object.
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "parseEnv",
        class_filter: None,
        runtime: "js_util_parse_env",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // #2514: util.toUSVString(value) → string with lone surrogates → U+FFFD.
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "toUSVString",
        class_filter: None,
        runtime: "js_util_to_usv_string",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "promisify",
        class_filter: None,
        runtime: "js_util_promisify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "callbackify",
        class_filter: None,
        runtime: "js_util_callbackify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "deprecate",
        class_filter: None,
        runtime: "js_util_deprecate",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "parseArgs",
        class_filter: None,
        runtime: "js_util_parse_args",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isPromise",
        class_filter: None,
        runtime: "js_util_types_is_promise",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isArrayBuffer",
        class_filter: None,
        runtime: "js_util_types_is_array_buffer",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isAnyArrayBuffer",
        class_filter: None,
        runtime: "js_util_types_is_any_array_buffer",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isSharedArrayBuffer",
        class_filter: None,
        runtime: "js_util_types_is_shared_array_buffer",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isArrayBufferView",
        class_filter: None,
        runtime: "js_util_types_is_array_buffer_view",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isTypedArray",
        class_filter: None,
        runtime: "js_util_types_is_typed_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isUint8Array",
        class_filter: None,
        runtime: "js_util_types_is_uint8_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isInt8Array",
        class_filter: None,
        runtime: "js_util_types_is_int8_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isInt16Array",
        class_filter: None,
        runtime: "js_util_types_is_int16_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isUint16Array",
        class_filter: None,
        runtime: "js_util_types_is_uint16_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isInt32Array",
        class_filter: None,
        runtime: "js_util_types_is_int32_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isUint32Array",
        class_filter: None,
        runtime: "js_util_types_is_uint32_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isFloat32Array",
        class_filter: None,
        runtime: "js_util_types_is_float32_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isFloat64Array",
        class_filter: None,
        runtime: "js_util_types_is_float64_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isUint8ClampedArray",
        class_filter: None,
        runtime: "js_util_types_is_uint8_clamped_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isBigInt64Array",
        class_filter: None,
        runtime: "js_util_types_is_big_int64_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isBigUint64Array",
        class_filter: None,
        runtime: "js_util_types_is_big_uint64_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isMap",
        class_filter: None,
        runtime: "js_util_types_is_map",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isMapIterator",
        class_filter: None,
        runtime: "js_util_types_is_map_iterator",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isProxy",
        class_filter: None,
        runtime: "js_util_types_is_proxy",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isSet",
        class_filter: None,
        runtime: "js_util_types_is_set",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isSetIterator",
        class_filter: None,
        runtime: "js_util_types_is_set_iterator",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isDate",
        class_filter: None,
        runtime: "js_util_types_is_date",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isRegExp",
        class_filter: None,
        runtime: "js_util_types_is_reg_exp",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isAsyncFunction",
        class_filter: None,
        runtime: "js_util_types_is_async_function",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isGeneratorFunction",
        class_filter: None,
        runtime: "js_util_types_is_generator_function",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isGeneratorObject",
        class_filter: None,
        runtime: "js_util_types_is_generator_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isNativeError",
        class_filter: None,
        runtime: "js_util_types_is_native_error",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isNumberObject",
        class_filter: None,
        runtime: "js_util_types_is_number_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isStringObject",
        class_filter: None,
        runtime: "js_util_types_is_string_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isBooleanObject",
        class_filter: None,
        runtime: "js_util_types_is_boolean_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isBoxedPrimitive",
        class_filter: None,
        runtime: "js_util_types_is_boxed_primitive",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "copyBytesFrom",
        class_filter: None,
        runtime: "js_buffer_copy_bytes_from",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "isAscii",
        class_filter: None,
        runtime: "js_buffer_is_ascii",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "isUtf8",
        class_filter: None,
        runtime: "js_buffer_is_utf8",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // node:buffer legacy web aliases. The globals already lower to these
    // runtime helpers; namespace and named imports should hit the same path.
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "atob",
        class_filter: None,
        runtime: "js_atob",
        args: &[NA_F64],
        ret: NR_STR,
    },
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "btoa",
        class_filter: None,
        runtime: "js_btoa",
        args: &[NA_F64],
        ret: NR_STR,
    },
    // Issue #1210: `buffer.transcode(source, fromEnc, toEnc)`.
    // Receiver-less Node-buffer export; arguments are NaN-boxed (source
    // is a Buffer pointer, encodings are strings). Returns a Buffer
    // pointer that must be NaN-boxed with POINTER_TAG by the dispatch
    // wrapper — `NR_PTR` handles that step.
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "transcode",
        class_filter: None,
        runtime: "js_buffer_transcode",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_PTR,
    },
    // Issue #1211: `import { resolveObjectURL } from "node:buffer"`.
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "resolveObjectURL",
        class_filter: None,
        runtime: "js_buffer_resolve_object_url",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // Issue #1211: `URL.createObjectURL(blob)` /
    // `URL.revokeObjectURL(url)` — modelled as receiver-less
    // `("url", "createObjectURL"/"revokeObjectURL")` so the static
    // method dispatch in `expr_call/module_static.rs` picks them up.
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "createObjectURL",
        class_filter: None,
        runtime: "js_url_create_object_url",
        args: &[NA_F64],
        ret: NR_STR,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "revokeObjectURL",
        class_filter: None,
        runtime: "js_url_revoke_object_url",
        args: &[NA_F64],
        ret: NR_VOID,
    },
];
