use super::*;

pub(super) const NODE_CORE_ROWS: &[NativeModSig] = &[
    // ========== Node inspector ==========
    NativeModSig {
        module: "inspector",
        has_receiver: false,
        method: "open",
        class_filter: None,
        runtime: "js_node_inspector_open",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: false,
        method: "close",
        class_filter: None,
        runtime: "js_node_inspector_close",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: false,
        method: "url",
        class_filter: None,
        runtime: "js_node_inspector_url",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: false,
        method: "waitForDebugger",
        class_filter: None,
        runtime: "js_node_inspector_wait_for_debugger",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: false,
        method: "Session",
        class_filter: None,
        runtime: "js_node_inspector_session_new",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "requestWillBeSent",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "responseReceived",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "loadingFinished",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "loadingFailed",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "dataSent",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "dataReceived",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "webSocketCreated",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "webSocketClosed",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "webSocketHandshakeResponseReceived",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: false,
        method: "Session",
        class_filter: None,
        runtime: "js_node_inspector_promises_session_new",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: true,
        method: "connect",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_connect",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: true,
        method: "connectToMainThread",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_connect_to_main_thread",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: true,
        method: "disconnect",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_disconnect",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: true,
        method: "post",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_post",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: true,
        method: "on",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_on",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: true,
        method: "once",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_once",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: true,
        method: "connect",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_connect",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: true,
        method: "connectToMainThread",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_connect_to_main_thread",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: true,
        method: "disconnect",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_disconnect",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: true,
        method: "post",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_post",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: true,
        method: "on",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_on",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: true,
        method: "once",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_once",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // ========== Node vm scaffold ==========
    // `createContext` is intentionally omitted here: it is implemented on main
    // (#4050) via the node_submodules thunk + `object::js_vm_create_context`,
    // which returns a usable context object. The remaining surface is the
    // shape-only scaffold (#4079) plus measureMemory validation (#4087).
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "createScript",
        class_filter: None,
        runtime: "js_vm_create_script",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "runInContext",
        class_filter: None,
        runtime: "js_vm_run_in_context",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "runInNewContext",
        class_filter: None,
        runtime: "js_vm_run_in_new_context",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "runInThisContext",
        class_filter: None,
        runtime: "js_vm_run_in_this_context",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "isContext",
        class_filter: None,
        runtime: "js_vm_is_context",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "compileFunction",
        class_filter: None,
        runtime: "js_vm_compile_function",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "measureMemory",
        class_filter: None,
        runtime: "js_vm_measure_memory",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "SourceTextModule",
        class_filter: None,
        runtime: "js_vm_source_text_module_new",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "SyntheticModule",
        class_filter: None,
        runtime: "js_vm_synthetic_module_new",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "status",
        class_filter: None,
        runtime: "js_vm_module_status",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "identifier",
        class_filter: None,
        runtime: "js_vm_module_identifier",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "error",
        class_filter: None,
        runtime: "js_vm_module_error",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "namespace",
        class_filter: None,
        runtime: "js_vm_module_namespace",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "dependencySpecifiers",
        class_filter: None,
        runtime: "js_vm_source_text_module_dependency_specifiers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "moduleRequests",
        class_filter: None,
        runtime: "js_vm_source_text_module_module_requests",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "status",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_module_status",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "status",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_module_status",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "identifier",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_module_identifier",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "identifier",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_module_identifier",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "error",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_module_error",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "error",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_module_error",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "namespace",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_module_namespace",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "namespace",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_module_namespace",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "link",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_module_link",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "link",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_module_link",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "evaluate",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_module_evaluate",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "evaluate",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_module_evaluate",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "dependencySpecifiers",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_dependency_specifiers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "moduleRequests",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_module_requests",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "createCachedData",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_create_cached_data",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "linkRequests",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_link_requests",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "instantiate",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_instantiate",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "hasTopLevelAwait",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_has_top_level_await",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "hasAsyncGraph",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_has_async_graph",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "setExport",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_synthetic_module_set_export",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // ========== Node module ==========
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "enableCompileCache",
        class_filter: None,
        runtime: "js_module_enable_compile_cache",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "flushCompileCache",
        class_filter: None,
        runtime: "js_module_flush_compile_cache",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "getCompileCacheDir",
        class_filter: None,
        runtime: "js_module_get_compile_cache_dir",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "getSourceMapsSupport",
        class_filter: None,
        runtime: "js_module_get_source_maps_support",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "isBuiltin",
        class_filter: None,
        runtime: "js_module_is_builtin",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "SourceMap",
        class_filter: None,
        runtime: "js_module_source_map_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "setSourceMapsSupport",
        class_filter: None,
        runtime: "js_module_set_source_maps_support",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "stripTypeScriptTypes",
        class_filter: None,
        runtime: "js_module_strip_typescript_types",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // #3120: module.findPackageJSON(specifier[, base]) — walks parent
    // directories from the resolved specifier looking for package.json.
    // `specifier` (string) and `base` (string or URL object) both ride in
    // the NaN-boxed F64 slot; a missing `base` is padded with TAG_UNDEFINED.
    NativeModSig {
        module: "module",
        has_receiver: false,
        method: "findPackageJSON",
        class_filter: None,
        runtime: "js_module_find_package_json",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // ========== Node TLS helper surface ==========
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "getCiphers",
        class_filter: None,
        runtime: "js_tls_get_ciphers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "getCACertificates",
        class_filter: None,
        runtime: "js_tls_get_ca_certificates",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "setDefaultCACertificates",
        class_filter: None,
        runtime: "js_tls_set_default_ca_certificates",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "checkServerIdentity",
        class_filter: None,
        runtime: "js_tls_check_server_identity",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "createSecureContext",
        class_filter: None,
        runtime: "js_tls_create_secure_context",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "SecureContext",
        class_filter: None,
        runtime: "js_tls_secure_context_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node test runner ==========
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "default",
        class_filter: None,
        runtime: "js_node_test_register",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "test",
        class_filter: None,
        runtime: "js_node_test_register",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "skip",
        class_filter: None,
        runtime: "js_node_test_skip",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "todo",
        class_filter: None,
        runtime: "js_node_test_todo",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "only",
        class_filter: None,
        runtime: "js_node_test_only",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "suite",
        class_filter: None,
        runtime: "js_node_test_register",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "describe",
        class_filter: None,
        runtime: "js_node_test_register",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "it",
        class_filter: None,
        runtime: "js_node_test_register",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "before",
        class_filter: None,
        runtime: "js_node_test_hook",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "after",
        class_filter: None,
        runtime: "js_node_test_hook",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "beforeEach",
        class_filter: None,
        runtime: "js_node_test_hook",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "afterEach",
        class_filter: None,
        runtime: "js_node_test_hook",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "run",
        class_filter: None,
        runtime: "js_node_test_run",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "fn",
        class_filter: None,
        runtime: "js_node_test_mock_fn",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "method",
        class_filter: None,
        runtime: "js_node_test_mock_method",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "getter",
        class_filter: None,
        runtime: "js_node_test_mock_method",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "setter",
        class_filter: None,
        runtime: "js_node_test_mock_method",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "property",
        class_filter: None,
        runtime: "js_node_test_mock_property",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "reset",
        class_filter: None,
        runtime: "js_node_test_mock_reset",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "restoreAll",
        class_filter: None,
        runtime: "js_node_test_mock_restore_all",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "setDefaultSnapshotSerializers",
        class_filter: None,
        runtime: "js_node_test_snapshot_set_default_serializers",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "setResolveSnapshotPath",
        class_filter: None,
        runtime: "js_node_test_snapshot_set_resolve_snapshot_path",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "enable",
        class_filter: Some("timers"),
        runtime: "js_node_test_mock_timers_enable",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "tick",
        class_filter: Some("timers"),
        runtime: "js_node_test_mock_timers_tick",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "runAll",
        class_filter: Some("timers"),
        runtime: "js_node_test_mock_timers_run_all",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "setTime",
        class_filter: Some("timers"),
        runtime: "js_node_test_mock_timers_set_time",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "test",
        has_receiver: false,
        method: "reset",
        class_filter: Some("timers"),
        runtime: "js_node_test_mock_timers_reset",
        args: &[],
        ret: NR_F64,
    },
    // ========== Node dgram deterministic loopback subset ==========
    NativeModSig {
        module: "dgram",
        has_receiver: false,
        method: "createSocket",
        class_filter: None,
        runtime: "js_dgram_create_socket",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: false,
        method: "Socket",
        class_filter: None,
        runtime: "js_dgram_create_socket",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "send",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_send",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "bind",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_bind",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "close",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_close",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "address",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_address",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "remoteAddress",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_remote_address",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "connect",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_connect",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "disconnect",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_disconnect",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "on",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_on",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "addListener",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_on",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "once",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_once",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "off",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_remove_listener",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "removeListener",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_remove_listener",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "emit",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_emit",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "listenerCount",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_listener_count",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "eventNames",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_event_names",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "addMembership",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_add_membership",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "dropMembership",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_drop_membership",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "addSourceSpecificMembership",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_add_source_membership",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "dropSourceSpecificMembership",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_drop_source_membership",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setBroadcast",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_broadcast",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setMulticastTTL",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_multicast_ttl",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setMulticastLoopback",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_multicast_loopback",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setMulticastInterface",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_multicast_interface",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setTTL",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_ttl",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setRecvBufferSize",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_recv_buffer_size",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setSendBufferSize",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_send_buffer_size",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "getRecvBufferSize",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_get_recv_buffer_size",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "getSendBufferSize",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_get_send_buffer_size",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "getSendQueueSize",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_zero",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "getSendQueueCount",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_zero",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "ref",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_chain",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "unref",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_chain",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    // ========== Node FS ==========
    NativeModSig {
        module: "fs",
        has_receiver: false,
        method: "_toUnixTimestamp",
        class_filter: None,
        runtime: "js_fs_to_unix_timestamp",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node TTY ==========
    NativeModSig {
        module: "tty",
        has_receiver: false,
        method: "isatty",
        class_filter: None,
        runtime: "js_tty_isatty",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tty",
        has_receiver: false,
        method: "ReadStream",
        class_filter: None,
        runtime: "js_tty_read_stream_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tty",
        has_receiver: false,
        method: "WriteStream",
        class_filter: None,
        runtime: "js_tty_write_stream_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node WASI ==========
    NativeModSig {
        module: "wasi",
        has_receiver: false,
        method: "WASI",
        class_filter: None,
        runtime: "js_wasi_constructor_call",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node OS ==========
    NativeModSig {
        module: "os",
        has_receiver: false,
        method: "getPriority",
        class_filter: None,
        runtime: "js_os_get_priority",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "os",
        has_receiver: false,
        method: "setPriority",
        class_filter: None,
        runtime: "js_os_set_priority",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // #3004 — `os.userInfo(options)` with a dynamic options object (variable,
    // function return, computed-key). The runtime inspects `options.encoding`
    // and returns Buffer text fields only on an exact `"buffer"` match. The
    // static-literal `{ encoding: "buffer" }` form is lowered separately to
    // `OsUserInfoBuffer`; this table entry handles everything else.
    NativeModSig {
        module: "os",
        has_receiver: false,
        method: "userInfo",
        class_filter: None,
        runtime: "js_os_user_info_options",
        args: &[NA_JSV],
        ret: NR_PTR,
    },
    // ========== Node URL ==========
    // `new Number/String/Boolean(...)` now lowers to
    // `Expr::BoxedPrimitiveNew` (see crates/perry-hir/src/lower/expr_new.rs)
    // and is emitted by codegen as a direct runtime call — no dispatch
    // table row needed.
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "fileURLToPath",
        class_filter: None,
        runtime: "js_url_file_url_to_path",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "fileURLToPathBuffer",
        class_filter: None,
        runtime: "js_url_file_url_to_path_buffer",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "pathToFileURL",
        class_filter: None,
        runtime: "js_url_path_to_file_url",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "domainToASCII",
        class_filter: None,
        runtime: "js_url_domain_to_ascii",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "domainToUnicode",
        class_filter: None,
        runtime: "js_url_domain_to_unicode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "urlToHttpOptions",
        class_filter: None,
        runtime: "js_url_to_http_options",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "URLPattern",
        class_filter: None,
        runtime: "js_url_pattern_constructor_call",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: true,
        method: "exec",
        class_filter: Some("URLPattern"),
        runtime: "js_url_pattern_exec",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: true,
        method: "test",
        class_filter: Some("URLPattern"),
        runtime: "js_url_pattern_test",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "Url",
        class_filter: None,
        runtime: "js_url_legacy_url_new",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "format",
        class_filter: None,
        runtime: "js_url_format",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "parse",
        class_filter: None,
        runtime: "js_url_legacy_parse",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "resolve",
        class_filter: None,
        runtime: "js_url_legacy_resolve",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "resolveObject",
        class_filter: None,
        runtime: "js_url_legacy_resolve_object",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // ========== Node punycode (deprecated, #2513) ==========
    NativeModSig {
        module: "punycode",
        has_receiver: false,
        method: "decode",
        class_filter: None,
        runtime: "js_punycode_decode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "punycode",
        has_receiver: false,
        method: "encode",
        class_filter: None,
        runtime: "js_punycode_encode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "punycode",
        has_receiver: false,
        method: "toASCII",
        class_filter: None,
        runtime: "js_punycode_to_ascii",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "punycode",
        has_receiver: false,
        method: "toUnicode",
        class_filter: None,
        runtime: "js_punycode_to_unicode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // punycode.ucs2 sub-namespace (#2607): decode(string)->code-point array,
    // encode(code-point array)->string. The array arg/return ride as a
    // NaN-boxed pointer in the NA_F64 slot.
    NativeModSig {
        module: "punycode.ucs2",
        has_receiver: false,
        method: "decode",
        class_filter: None,
        runtime: "js_punycode_ucs2_decode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "punycode.ucs2",
        has_receiver: false,
        method: "encode",
        class_filter: None,
        runtime: "js_punycode_ucs2_encode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node console ==========
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "log",
        class_filter: None,
        runtime: "js_console_log_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "info",
        class_filter: None,
        runtime: "js_console_info_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "debug",
        class_filter: None,
        runtime: "js_console_debug_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "dirxml",
        class_filter: None,
        runtime: "js_console_log_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "error",
        class_filter: None,
        runtime: "js_console_error_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "warn",
        class_filter: None,
        runtime: "js_console_warn_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "assert",
        class_filter: None,
        runtime: "js_console_assert_spread",
        args: &[NA_F64, NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "dir",
        class_filter: None,
        runtime: "js_console_log_dynamic",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "trace",
        class_filter: None,
        runtime: "js_console_trace",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "table",
        class_filter: None,
        runtime: "js_console_table",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "clear",
        class_filter: None,
        runtime: "js_console_clear",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "count",
        class_filter: None,
        runtime: "js_console_count",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "countReset",
        class_filter: None,
        runtime: "js_console_count_reset",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "time",
        class_filter: None,
        runtime: "js_console_time",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "timeEnd",
        class_filter: None,
        runtime: "js_console_time_end",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "timeLog",
        class_filter: None,
        runtime: "js_console_time_log",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "groupEnd",
        class_filter: None,
        runtime: "js_console_group_end",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "group",
        class_filter: None,
        runtime: "js_console_group_begin",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "groupCollapsed",
        class_filter: None,
        runtime: "js_console_group_begin",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "profile",
        class_filter: None,
        runtime: "js_console_noop",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "profileEnd",
        class_filter: None,
        runtime: "js_console_noop",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "timeStamp",
        class_filter: None,
        runtime: "js_console_noop",
        args: &[],
        ret: NR_VOID,
    },
    // ========== Node assert ==========
    // Root-callable `assert(value, message?)` — HIR lowers
    // `import assert from "node:assert"; assert(x, m)` to a
    // `NativeMethodCall { module: "assert", method: "default" }`.
    // Route it to `js_assert_ok` (Node's default export aliases
    // `assert.ok`). Same for `node:assert/strict`.
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "default",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "default",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // `assert.strict(value, msg?)` — the `.strict` namespace itself is
    // callable and behaves like `assert.strict.ok`.
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "strict",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "strict",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "ok",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "fail",
        class_filter: None,
        runtime: "js_assert_fail",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "equal",
        class_filter: None,
        runtime: "js_assert_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "notEqual",
        class_filter: None,
        runtime: "js_assert_not_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "strictEqual",
        class_filter: None,
        runtime: "js_assert_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "notStrictEqual",
        class_filter: None,
        runtime: "js_assert_not_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "deepEqual",
        class_filter: None,
        runtime: "js_assert_deep_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "notDeepEqual",
        class_filter: None,
        runtime: "js_assert_not_deep_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "deepStrictEqual",
        class_filter: None,
        runtime: "js_assert_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "partialDeepStrictEqual",
        class_filter: None,
        runtime: "js_assert_partial_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "notDeepStrictEqual",
        class_filter: None,
        runtime: "js_assert_not_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "match",
        class_filter: None,
        runtime: "js_assert_match",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "doesNotMatch",
        class_filter: None,
        runtime: "js_assert_does_not_match",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "throws",
        class_filter: None,
        runtime: "js_assert_throws",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "doesNotThrow",
        class_filter: None,
        runtime: "js_assert_does_not_throw",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "rejects",
        class_filter: None,
        runtime: "js_assert_rejects",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "doesNotReject",
        class_filter: None,
        runtime: "js_assert_does_not_reject",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "ifError",
        class_filter: None,
        runtime: "js_assert_if_error",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "ok",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "fail",
        class_filter: None,
        runtime: "js_assert_fail",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "equal",
        class_filter: None,
        runtime: "js_assert_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "notEqual",
        class_filter: None,
        runtime: "js_assert_not_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "deepEqual",
        class_filter: None,
        runtime: "js_assert_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "notDeepEqual",
        class_filter: None,
        runtime: "js_assert_not_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "strictEqual",
        class_filter: None,
        runtime: "js_assert_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "notStrictEqual",
        class_filter: None,
        runtime: "js_assert_not_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "deepStrictEqual",
        class_filter: None,
        runtime: "js_assert_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "partialDeepStrictEqual",
        class_filter: None,
        runtime: "js_assert_partial_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "notDeepStrictEqual",
        class_filter: None,
        runtime: "js_assert_not_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "match",
        class_filter: None,
        runtime: "js_assert_match",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "doesNotMatch",
        class_filter: None,
        runtime: "js_assert_does_not_match",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "throws",
        class_filter: None,
        runtime: "js_assert_throws",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "doesNotThrow",
        class_filter: None,
        runtime: "js_assert_does_not_throw",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "rejects",
        class_filter: None,
        runtime: "js_assert_rejects",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "doesNotReject",
        class_filter: None,
        runtime: "js_assert_does_not_reject",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "ifError",
        class_filter: None,
        runtime: "js_assert_if_error",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node util ==========
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "inspect",
        class_filter: None,
        runtime: "js_util_inspect",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "convertProcessSignalToExitCode",
        class_filter: None,
        runtime: "js_util_convert_process_signal_to_exit_code",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "debuglog",
        class_filter: None,
        runtime: "js_util_debuglog",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "debug",
        class_filter: None,
        runtime: "js_util_debuglog",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "diff",
        class_filter: None,
        runtime: "js_util_diff",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "inherits",
        class_filter: None,
        runtime: "js_util_inherits",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "isArray",
        class_filter: None,
        runtime: "js_array_is_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "isDeepStrictEqual",
        class_filter: None,
        runtime: "js_util_is_deep_strict_equal",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "stripVTControlCharacters",
        class_filter: None,
        runtime: "js_util_strip_vt_control_characters",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "styleText",
        class_filter: None,
        runtime: "js_util_style_text",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    // #2514: util.getSystemErrorName/Message(errno) + getSystemErrorMap().
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "getSystemErrorName",
        class_filter: None,
        runtime: "js_util_get_system_error_name",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "getSystemErrorMessage",
        class_filter: None,
        runtime: "js_util_get_system_error_message",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "getSystemErrorMap",
        class_filter: None,
        runtime: "js_util_get_system_error_map",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "aborted",
        class_filter: None,
        runtime: "js_util_aborted",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "transferableAbortController",
        class_filter: None,
        runtime: "js_util_transferable_abort_controller",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "transferableAbortSignal",
        class_filter: None,
        runtime: "js_util_transferable_abort_signal",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "getCallSites",
        class_filter: None,
        runtime: "js_util_get_call_sites",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // #2514: util.parseEnv(content) → object.
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "parseEnv",
        class_filter: None,
        runtime: "js_util_parse_env",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // #2514: util.toUSVString(value) → string with lone surrogates → U+FFFD.
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "toUSVString",
        class_filter: None,
        runtime: "js_util_to_usv_string",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // #2514: util.setTraceSigInt(enable) → validate boolean, return undefined.
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "setTraceSigInt",
        class_filter: None,
        runtime: "js_util_set_trace_sig_int",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "promisify",
        class_filter: None,
        runtime: "js_util_promisify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "callbackify",
        class_filter: None,
        runtime: "js_util_callbackify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "deprecate",
        class_filter: None,
        runtime: "js_util_deprecate",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util",
        has_receiver: false,
        method: "parseArgs",
        class_filter: None,
        runtime: "js_util_parse_args",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isArgumentsObject",
        class_filter: None,
        runtime: "js_util_types_is_arguments_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isPromise",
        class_filter: None,
        runtime: "js_util_types_is_promise",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isBigIntObject",
        class_filter: None,
        runtime: "js_util_types_is_big_int_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isArrayBuffer",
        class_filter: None,
        runtime: "js_util_types_is_array_buffer",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isAnyArrayBuffer",
        class_filter: None,
        runtime: "js_util_types_is_any_array_buffer",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isSharedArrayBuffer",
        class_filter: None,
        runtime: "js_util_types_is_shared_array_buffer",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isArrayBufferView",
        class_filter: None,
        runtime: "js_util_types_is_array_buffer_view",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isDataView",
        class_filter: None,
        runtime: "js_util_types_is_data_view",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isTypedArray",
        class_filter: None,
        runtime: "js_util_types_is_typed_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isUint8Array",
        class_filter: None,
        runtime: "js_util_types_is_uint8_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isInt8Array",
        class_filter: None,
        runtime: "js_util_types_is_int8_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isInt16Array",
        class_filter: None,
        runtime: "js_util_types_is_int16_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isUint16Array",
        class_filter: None,
        runtime: "js_util_types_is_uint16_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isInt32Array",
        class_filter: None,
        runtime: "js_util_types_is_int32_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isUint32Array",
        class_filter: None,
        runtime: "js_util_types_is_uint32_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isFloat16Array",
        class_filter: None,
        runtime: "js_util_types_is_float16_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isFloat32Array",
        class_filter: None,
        runtime: "js_util_types_is_float32_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isFloat64Array",
        class_filter: None,
        runtime: "js_util_types_is_float64_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isUint8ClampedArray",
        class_filter: None,
        runtime: "js_util_types_is_uint8_clamped_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isBigInt64Array",
        class_filter: None,
        runtime: "js_util_types_is_big_int64_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isBigUint64Array",
        class_filter: None,
        runtime: "js_util_types_is_big_uint64_array",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isMap",
        class_filter: None,
        runtime: "js_util_types_is_map",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isMapIterator",
        class_filter: None,
        runtime: "js_util_types_is_map_iterator",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isProxy",
        class_filter: None,
        runtime: "js_util_types_is_proxy",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isExternal",
        class_filter: None,
        runtime: "js_util_types_is_external",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isModuleNamespaceObject",
        class_filter: None,
        runtime: "js_util_types_is_module_namespace_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isSet",
        class_filter: None,
        runtime: "js_util_types_is_set",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isSetIterator",
        class_filter: None,
        runtime: "js_util_types_is_set_iterator",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isWeakMap",
        class_filter: None,
        runtime: "js_util_types_is_weak_map",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isWeakSet",
        class_filter: None,
        runtime: "js_util_types_is_weak_set",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isDate",
        class_filter: None,
        runtime: "js_util_types_is_date",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isRegExp",
        class_filter: None,
        runtime: "js_util_types_is_reg_exp",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isAsyncFunction",
        class_filter: None,
        runtime: "js_util_types_is_async_function",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isGeneratorFunction",
        class_filter: None,
        runtime: "js_util_types_is_generator_function",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isGeneratorObject",
        class_filter: None,
        runtime: "js_util_types_is_generator_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isNativeError",
        class_filter: None,
        runtime: "js_util_types_is_native_error",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isKeyObject",
        class_filter: None,
        runtime: "js_util_types_is_key_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isCryptoKey",
        class_filter: None,
        runtime: "js_util_types_is_crypto_key",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isNumberObject",
        class_filter: None,
        runtime: "js_util_types_is_number_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isStringObject",
        class_filter: None,
        runtime: "js_util_types_is_string_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isBooleanObject",
        class_filter: None,
        runtime: "js_util_types_is_boolean_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isSymbolObject",
        class_filter: None,
        runtime: "js_util_types_is_symbol_object",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "util/types",
        has_receiver: false,
        method: "isBoxedPrimitive",
        class_filter: None,
        runtime: "js_util_types_is_boxed_primitive",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "copyBytesFrom",
        class_filter: None,
        runtime: "js_buffer_copy_bytes_from",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_PTR,
    },
    // #2901: TC39 `Uint8Array.fromBase64(str, opts)` / `fromHex(str)`.
    // Routed via the buffer module (Uint8Array ≡ Buffer in Perry); the
    // runtime decodes strictly into a fresh BufferHeader.
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "fromBase64",
        class_filter: None,
        runtime: "js_u8_from_base64",
        args: &[NA_STR, NA_F64],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "fromHex",
        class_filter: None,
        runtime: "js_u8_from_hex",
        args: &[NA_STR],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "isAscii",
        class_filter: None,
        runtime: "js_buffer_is_ascii",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "isUtf8",
        class_filter: None,
        runtime: "js_buffer_is_utf8",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // node:buffer legacy web aliases. The globals already lower to these
    // runtime helpers; namespace and named imports should hit the same path.
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "atob",
        class_filter: None,
        runtime: "js_atob",
        args: &[NA_F64],
        ret: NR_STR,
    },
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "btoa",
        class_filter: None,
        runtime: "js_btoa",
        args: &[NA_F64],
        ret: NR_STR,
    },
    // Issue #1210: `buffer.transcode(source, fromEnc, toEnc)`.
    // Receiver-less Node-buffer export; arguments are NaN-boxed (source
    // is a Buffer pointer, encodings are strings). Returns a Buffer
    // pointer that must be NaN-boxed with POINTER_TAG by the dispatch
    // wrapper — `NR_PTR` handles that step.
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "transcode",
        class_filter: None,
        runtime: "js_buffer_transcode",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_PTR,
    },
    // Issue #1211: `import { resolveObjectURL } from "node:buffer"`.
    NativeModSig {
        module: "buffer",
        has_receiver: false,
        method: "resolveObjectURL",
        class_filter: None,
        runtime: "js_buffer_resolve_object_url",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // Issue #1211: `URL.createObjectURL(blob)` /
    // `URL.revokeObjectURL(url)` — modelled as receiver-less
    // `("url", "createObjectURL"/"revokeObjectURL")` so the static
    // method dispatch in `expr_call/module_static.rs` picks them up.
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "createObjectURL",
        class_filter: None,
        runtime: "js_url_create_object_url",
        args: &[NA_F64],
        ret: NR_STR,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "revokeObjectURL",
        class_filter: None,
        runtime: "js_url_revoke_object_url",
        args: &[NA_F64],
        ret: NR_VOID,
    },
];
