use super::*;

/// `process` module native-dispatch rows, extracted from `node_core.rs`
/// to keep that file under the 2000-line cap. Spliced into the combined
/// table by `native_table::mod` via `extend_from_slice`.
pub(super) const NODE_CORE_PROCESS_ROWS: &[NativeModSig] = &[
    // ========== Node process core helpers ==========
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "abort",
        class_filter: None,
        runtime: "js_process_abort",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "umask",
        class_filter: None,
        runtime: "js_process_umask_set",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "threadCpuUsage",
        class_filter: None,
        runtime: "js_process_thread_cpu_usage",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "availableMemory",
        class_filter: None,
        runtime: "js_process_available_memory",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "constrainedMemory",
        class_filter: None,
        runtime: "js_process_constrained_memory",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "getuid",
        class_filter: None,
        runtime: "js_process_getuid",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "geteuid",
        class_filter: None,
        runtime: "js_process_geteuid",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "getgid",
        class_filter: None,
        runtime: "js_process_getgid",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "getegid",
        class_filter: None,
        runtime: "js_process_getegid",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "emitWarning",
        class_filter: None,
        runtime: "js_process_emit_warning",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "cpuUsage",
        class_filter: None,
        runtime: "js_process_cpu_usage",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "resourceUsage",
        class_filter: None,
        runtime: "js_process_resource_usage",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "getActiveResourcesInfo",
        class_filter: None,
        runtime: "js_process_active_resources_info",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "binding",
        class_filter: None,
        runtime: "js_process_binding",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "_linkedBinding",
        class_filter: None,
        runtime: "js_process_linked_binding",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "dlopen",
        class_filter: None,
        runtime: "js_process_dlopen",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "_rawDebug",
        class_filter: None,
        runtime: "js_process_raw_debug",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "_debugProcess",
        class_filter: None,
        runtime: "js_process_debug_process",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "_debugEnd",
        class_filter: None,
        runtime: "js_process_debug_end",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "_startProfilerIdleNotifier",
        class_filter: None,
        runtime: "js_process_start_profiler_idle_notifier",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "_stopProfilerIdleNotifier",
        class_filter: None,
        runtime: "js_process_stop_profiler_idle_notifier",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "reallyExit",
        class_filter: None,
        runtime: "js_process_really_exit",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "_fatalException",
        class_filter: None,
        runtime: "js_process_fatal_exception",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "_tickCallback",
        class_filter: None,
        runtime: "js_process_tick_callback",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "_getActiveHandles",
        class_filter: None,
        runtime: "js_process_get_active_handles",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "_getActiveRequests",
        class_filter: None,
        runtime: "js_process_get_active_requests",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "openStdin",
        class_filter: None,
        runtime: "js_process_open_stdin",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "_kill",
        class_filter: None,
        runtime: "js_process_internal_kill",
        args: &[],
        ret: NR_F64,
    },
    // ========== Node process EventEmitter ==========
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "on",
        class_filter: None,
        runtime: "js_process_on",
        args: &[NA_JSV, NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "addListener",
        class_filter: None,
        runtime: "js_process_add_listener",
        args: &[NA_JSV, NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "once",
        class_filter: None,
        runtime: "js_process_once",
        args: &[NA_JSV, NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "prependListener",
        class_filter: None,
        runtime: "js_process_prepend_listener",
        args: &[NA_JSV, NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "prependOnceListener",
        class_filter: None,
        runtime: "js_process_prepend_once_listener",
        args: &[NA_JSV, NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "emit",
        class_filter: None,
        runtime: "js_process_emit",
        args: &[NA_JSV, NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "removeListener",
        class_filter: None,
        runtime: "js_process_remove_listener",
        args: &[NA_JSV, NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "off",
        class_filter: None,
        runtime: "js_process_off",
        args: &[NA_JSV, NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "removeAllListeners",
        class_filter: None,
        runtime: "js_process_remove_all_listeners",
        args: &[NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "listenerCount",
        class_filter: None,
        runtime: "js_process_listener_count",
        args: &[NA_JSV, NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "listeners",
        class_filter: None,
        runtime: "js_process_listeners",
        args: &[NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "rawListeners",
        class_filter: None,
        runtime: "js_process_raw_listeners",
        args: &[NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "eventNames",
        class_filter: None,
        runtime: "js_process_event_names",
        args: &[],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setMaxListeners",
        class_filter: None,
        runtime: "js_process_set_max_listeners",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "getMaxListeners",
        class_filter: None,
        runtime: "js_process_get_max_listeners",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "getBuiltinModule",
        class_filter: None,
        runtime: "js_process_get_builtin_module",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "sourceMapsEnabled",
        class_filter: None,
        runtime: "js_process_source_maps_enabled",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setSourceMapsEnabled",
        class_filter: None,
        runtime: "js_process_set_source_maps_enabled",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "hasUncaughtExceptionCaptureCallback",
        class_filter: None,
        runtime: "js_process_has_uncaught_exception_capture_callback",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setUncaughtExceptionCaptureCallback",
        class_filter: None,
        runtime: "js_process_set_uncaught_exception_capture_callback",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "addUncaughtExceptionCaptureCallback",
        class_filter: None,
        runtime: "js_process_add_uncaught_exception_capture_callback",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // #2135 (Node process parity): process.loadEnvFile(path?) — pass the
    // full JS value so runtime validation can accept strings, Buffers,
    // file: URLs, and omitted/undefined/null defaults.
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "loadEnvFile",
        class_filter: None,
        runtime: "js_process_load_env_file",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    // #3108 (Node process parity): process.sourceMapsEnabled getter — reads
    // the live flag toggled by setSourceMapsEnabled, returns a boolean.
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "sourceMapsEnabled",
        class_filter: None,
        runtime: "js_process_source_maps_enabled",
        args: &[],
        ret: NR_F64,
    },
    // #3108 (Node process parity): process.setSourceMapsEnabled(enabled)
    // toggles the live source-map flag. Pass the full JS value so the
    // runtime can reject non-boolean arguments with ERR_INVALID_ARG_TYPE.
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setSourceMapsEnabled",
        class_filter: None,
        runtime: "js_process_set_source_maps_enabled",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // #2135 (Node process parity): process.getgroups() — Array<number>
    // of supplementary GIDs from libc::getgroups (empty on non-unix).
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "getgroups",
        class_filter: None,
        runtime: "js_process_getgroups",
        args: &[],
        ret: NR_F64,
    },
    // #2135 (Node process parity): POSIX credential setters — single
    // numeric ID arg, void return.
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setuid",
        class_filter: None,
        runtime: "js_process_setuid",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "seteuid",
        class_filter: None,
        runtime: "js_process_seteuid",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setgid",
        class_filter: None,
        runtime: "js_process_setgid",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setegid",
        class_filter: None,
        runtime: "js_process_setegid",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    // #2135: process.setgroups(groups[]) — JSValue array of numeric GIDs.
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "setgroups",
        class_filter: None,
        runtime: "js_process_setgroups",
        args: &[NA_JSV],
        ret: NR_VOID,
    },
    // #2135: process.initgroups(user, extra_gid) — username + numeric GID.
    NativeModSig {
        module: "process",
        has_receiver: false,
        method: "initgroups",
        class_filter: None,
        runtime: "js_process_initgroups",
        args: &[NA_JSV, NA_F64],
        ret: NR_VOID,
    },
];
