//! TLS native-dispatch rows (`tls.createServer`/`tls.Server`/`TLSSocket`
//! lifecycle + event handlers, plus the TLSSocket-shaped `net` certificate/
//! session/cipher/protocol introspection methods). Split out of
//! `net_events.rs` (#3196-#3200) to keep that file under the file-size gate.
//! Assembled into `NATIVE_MODULE_TABLE` by `mod.rs` right after the
//! `NET_EVENTS_ROWS` slice so dispatch order matches the original layout.

use super::*;

pub(super) const TLS_EVENTS_ROWS: &[NativeModSig] = &[
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "createServer",
        class_filter: None,
        runtime: "js_tls_create_server",
        args: &[NA_JSV, NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "Server",
        class_filter: None,
        runtime: "js_tls_create_server",
        args: &[NA_JSV, NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: false,
        method: "TLSSocket",
        class_filter: None,
        runtime: "js_tls_tlssocket_constructor",
        args: &[NA_JSV, NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "listen",
        class_filter: Some("Server"),
        runtime: "js_tls_server_listen",
        args: &[NA_F64, NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "close",
        class_filter: Some("Server"),
        runtime: "js_tls_server_close",
        args: &[NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "address",
        class_filter: Some("Server"),
        runtime: "js_tls_server_address",
        args: &[],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "on",
        class_filter: Some("Server"),
        runtime: "js_tls_server_on",
        args: &[NA_STR, NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "addListener",
        class_filter: Some("Server"),
        runtime: "js_tls_server_on",
        args: &[NA_STR, NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "once",
        class_filter: Some("Server"),
        runtime: "js_tls_server_once",
        args: &[NA_STR, NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "off",
        class_filter: Some("Server"),
        runtime: "js_tls_server_remove_listener",
        args: &[NA_STR, NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "removeListener",
        class_filter: Some("Server"),
        runtime: "js_tls_server_remove_listener",
        args: &[NA_STR, NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "removeAllListeners",
        class_filter: Some("Server"),
        runtime: "js_tls_server_remove_all_listeners",
        args: &[NA_STR],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "listenerCount",
        class_filter: Some("Server"),
        runtime: "js_tls_server_listener_count",
        args: &[NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "eventNames",
        class_filter: Some("Server"),
        runtime: "js_tls_server_event_names",
        args: &[],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "setSecureContext",
        class_filter: Some("Server"),
        runtime: "js_tls_server_set_secure_context",
        args: &[NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "getTicketKeys",
        class_filter: Some("Server"),
        runtime: "js_tls_server_get_ticket_keys",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tls",
        has_receiver: true,
        method: "setTicketKeys",
        class_filter: Some("Server"),
        runtime: "js_tls_server_set_ticket_keys",
        args: &[NA_JSV],
        ret: NR_PTR,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "getProtocol",
        class_filter: Some("Socket"),
        runtime: "js_tls_socket_get_protocol",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "getCipher",
        class_filter: Some("Socket"),
        runtime: "js_tls_socket_get_cipher",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "getPeerCertificate",
        class_filter: Some("Socket"),
        runtime: "js_tls_socket_get_peer_certificate",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "getCertificate",
        class_filter: Some("Socket"),
        runtime: "js_tls_socket_get_certificate",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "getSession",
        class_filter: Some("Socket"),
        runtime: "js_tls_socket_get_session",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "isSessionReused",
        class_filter: Some("Socket"),
        runtime: "js_tls_socket_is_session_reused",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "exportKeyingMaterial",
        class_filter: Some("Socket"),
        runtime: "js_tls_socket_export_keying_material",
        args: &[NA_F64, NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "setMaxSendFragment",
        class_filter: Some("Socket"),
        runtime: "js_tls_socket_set_max_send_fragment",
        args: &[NA_F64],
        ret: NR_F64,
    },
];
